package com.zzst.icmp.entity;

/**
 * ZTEquipmentBackupId generated by MyEclipse Persistence Tools
 */

public class ZTEquipmentBackupId implements java.io.Serializable {

	// Fields
	private static final long serialVersionUID = 1L;

	private String equipmentId;

	private String backupEquipmentId;

	// Constructors

	/** default constructor */
	public ZTEquipmentBackupId() {
	}

	/** full constructor */
	public ZTEquipmentBackupId(String equipmentId, String backupEquipmentId) {
		this.equipmentId = equipmentId;
		this.backupEquipmentId = backupEquipmentId;
	}

	// Property accessors

	public String getEquipmentId() {
		return this.equipmentId;
	}

	public void setEquipmentId(String equipmentId) {
		this.equipmentId = equipmentId;
	}

	public String getBackupEquipmentId() {
		return this.backupEquipmentId;
	}

	public void setBackupEquipmentId(String backupEquipmentId) {
		this.backupEquipmentId = backupEquipmentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZTEquipmentBackupId))
			return false;
		ZTEquipmentBackupId castOther = (ZTEquipmentBackupId) other;

		return ((this.getEquipmentId() == castOther.getEquipmentId()) || (this
				.getEquipmentId() != null
				&& castOther.getEquipmentId() != null && this.getEquipmentId()
				.equals(castOther.getEquipmentId())))
				&& ((this.getBackupEquipmentId() == castOther
						.getBackupEquipmentId()) || (this
						.getBackupEquipmentId() != null
						&& castOther.getBackupEquipmentId() != null && this
						.getBackupEquipmentId().equals(
								castOther.getBackupEquipmentId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getEquipmentId() == null ? 0 : this.getEquipmentId()
						.hashCode());
		result = 37
				* result
				+ (getBackupEquipmentId() == null ? 0 : this
						.getBackupEquipmentId().hashCode());
		return result;
	}

}