package com.zzst.icmp.entity;

import java.util.Date;

/**
 * ZTMeetingdetailCost generated by MyEclipse Persistence Tools
 */

public class ZTMeetingdetailCost implements java.io.Serializable {

	// Fields
	private static final long serialVersionUID = 1L;

	private String id;

	private String meetingDetailId;

	private String costItem;

	private Integer cout;

	private Integer costValue;

	private String createUserId;

	private Date createTime;

	private Integer status;

	private String description;

	private Long revision;

	private Date dbmsTime;

	// Constructors

	/** default constructor */
	public ZTMeetingdetailCost() {
	}

	/** minimal constructor */
	public ZTMeetingdetailCost(String meetingDetailId) {
		this.meetingDetailId = meetingDetailId;
	}

	/** full constructor */
	public ZTMeetingdetailCost(String meetingDetailId, String costItem,
			Integer cout, Integer costValue, String createUserId,
			Date createTime, Integer status, String description, Long revision,
			Date dbmsTime) {
		this.meetingDetailId = meetingDetailId;
		this.costItem = costItem;
		this.cout = cout;
		this.costValue = costValue;
		this.createUserId = createUserId;
		this.createTime = createTime;
		this.status = status;
		this.description = description;
		this.revision = revision;
		this.dbmsTime = dbmsTime;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMeetingDetailId() {
		return this.meetingDetailId;
	}

	public void setMeetingDetailId(String meetingDetailId) {
		this.meetingDetailId = meetingDetailId;
	}

	public String getCostItem() {
		return this.costItem;
	}

	public void setCostItem(String costItem) {
		this.costItem = costItem;
	}

	public Integer getCout() {
		return this.cout;
	}

	public void setCout(Integer cout) {
		this.cout = cout;
	}

	public Integer getCostValue() {
		return this.costValue;
	}

	public void setCostValue(Integer costValue) {
		this.costValue = costValue;
	}

	public String getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Long getRevision() {
		return this.revision;
	}

	public void setRevision(Long revision) {
		this.revision = revision;
	}

	public Date getDbmsTime() {
		return this.dbmsTime;
	}

	public void setDbmsTime(Date dbmsTime) {
		this.dbmsTime = dbmsTime;
	}

}