package com.zzst.icmp.entity;

import java.util.Date;

/**
 * ZTRole generated by MyEclipse Persistence Tools
 */

public class ZTRole implements java.io.Serializable {

	// Fields
	private static final long serialVersionUID = 1L;

	private String roleId;

	private String roleName;

	private String createDate;

	private String createBy;

	private String status;

	private String note;

	private Date dbmsTime;

	// Constructors

	/** default constructor */
	public ZTRole() {
	}

	/** minimal constructor */
	public ZTRole(String roleName) {
		this.roleName = roleName;
	}

	/** full constructor */
	public ZTRole(String roleName, String createDate, String createBy,
			String status, String note, Date dbmsTime) {
		this.roleName = roleName;
		this.createDate = createDate;
		this.createBy = createBy;
		this.status = status;
		this.note = note;
		this.dbmsTime = dbmsTime;
	}

	// Property accessors

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getDbmsTime() {
		return this.dbmsTime;
	}

	public void setDbmsTime(Date dbmsTime) {
		this.dbmsTime = dbmsTime;
	}

}