package com.zzst.icmp.entity;

import java.util.Date;

/**
 * ZTEquipmentBackup generated by MyEclipse Persistence Tools
 */

public class ZTEquipmentBackup implements java.io.Serializable {

	// Fields
	private static final long serialVersionUID = 1L;

	private ZTEquipmentBackupId id;

	private String createUserId;

	private Date createDate;

	private Integer backupLevel;

	private Integer employ;

	private Integer status;

	private String description;

	private Integer equipmentType;

	private Date dbmsTime;

	// Constructors

	/** default constructor */
	public ZTEquipmentBackup() {
	}

	/** minimal constructor */
	public ZTEquipmentBackup(ZTEquipmentBackupId id) {
		this.id = id;
	}

	/** full constructor */
	public ZTEquipmentBackup(ZTEquipmentBackupId id, String createUserId,
			Date createDate, Integer backupLevel, Integer employ,
			Integer status, String description, Integer equipmentType,
			Date dbmsTime) {
		this.id = id;
		this.createUserId = createUserId;
		this.createDate = createDate;
		this.backupLevel = backupLevel;
		this.employ = employ;
		this.status = status;
		this.description = description;
		this.equipmentType = equipmentType;
		this.dbmsTime = dbmsTime;
	}

	// Property accessors

	public ZTEquipmentBackupId getId() {
		return this.id;
	}

	public void setId(ZTEquipmentBackupId id) {
		this.id = id;
	}

	public String getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getBackupLevel() {
		return this.backupLevel;
	}

	public void setBackupLevel(Integer backupLevel) {
		this.backupLevel = backupLevel;
	}

	public Integer getEmploy() {
		return this.employ;
	}

	public void setEmploy(Integer employ) {
		this.employ = employ;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getEquipmentType() {
		return this.equipmentType;
	}

	public void setEquipmentType(Integer equipmentType) {
		this.equipmentType = equipmentType;
	}

	public Date getDbmsTime() {
		return this.dbmsTime;
	}

	public void setDbmsTime(Date dbmsTime) {
		this.dbmsTime = dbmsTime;
	}

}