package com.zzst.icmp.entity;

/**
 * ZTMeetingroomEquipmentId generated by MyEclipse Persistence Tools
 */

public class ZTMeetingroomEquipmentId implements java.io.Serializable {

	// Fields
	private static final long serialVersionUID = 1L;

	private String roomId;

	private String equipmentId;

	// Constructors

	/** default constructor */
	public ZTMeetingroomEquipmentId() {
	}

	/** full constructor */
	public ZTMeetingroomEquipmentId(String roomId, String equipmentId) {
		this.roomId = roomId;
		this.equipmentId = equipmentId;
	}

	// Property accessors

	public String getRoomId() {
		return this.roomId;
	}

	public void setRoomId(String roomId) {
		this.roomId = roomId;
	}

	public String getEquipmentId() {
		return this.equipmentId;
	}

	public void setEquipmentId(String equipmentId) {
		this.equipmentId = equipmentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZTMeetingroomEquipmentId))
			return false;
		ZTMeetingroomEquipmentId castOther = (ZTMeetingroomEquipmentId) other;

		return ((this.getRoomId() == castOther.getRoomId()) || (this
				.getRoomId() != null
				&& castOther.getRoomId() != null && this.getRoomId().equals(
				castOther.getRoomId())))
				&& ((this.getEquipmentId() == castOther.getEquipmentId()) || (this
						.getEquipmentId() != null
						&& castOther.getEquipmentId() != null && this
						.getEquipmentId().equals(castOther.getEquipmentId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRoomId() == null ? 0 : this.getRoomId().hashCode());
		result = 37
				* result
				+ (getEquipmentId() == null ? 0 : this.getEquipmentId()
						.hashCode());
		return result;
	}

}