package com.zzst.icmp.entity;

import java.util.Date;

/**
 * ZTMeetingroom generated by MyEclipse Persistence Tools
 */

public class ZTMeetingroom implements java.io.Serializable {

	// Fields
	private static final long serialVersionUID = 1L;

	private String meetingroomId;

	private String meetingroomName;

	private String roomNo;

	private Integer meetingroomType;

	private Integer capacity;

	private String planeImg;

	private String pictureImg;

	private String meetingroomUrl;

	private Integer status;

	private String adminId;

	private String departmentId;

	private String addressId;

	private String description;

	private Long revision;

	private String provinceId;

	private String info1;

	private String info2;

	private String info3;

	private String info4;

	private String infor5;

	private String roomPca;

	private Date dbmsTime;

	// Constructors

	/** default constructor */
	public ZTMeetingroom() {
	}

	/** full constructor */
	public ZTMeetingroom(String meetingroomName, String roomNo,
			Integer meetingroomType, Integer capacity, String planeImg,
			String pictureImg, String meetingroomUrl, Integer status,
			String adminId, String departmentId, String addressId,
			String description, Long revision, String provinceId, String info1,
			String info2, String info3, String info4, String infor5,
			String roomPca, Date dbmsTime) {
		this.meetingroomName = meetingroomName;
		this.roomNo = roomNo;
		this.meetingroomType = meetingroomType;
		this.capacity = capacity;
		this.planeImg = planeImg;
		this.pictureImg = pictureImg;
		this.meetingroomUrl = meetingroomUrl;
		this.status = status;
		this.adminId = adminId;
		this.departmentId = departmentId;
		this.addressId = addressId;
		this.description = description;
		this.revision = revision;
		this.provinceId = provinceId;
		this.info1 = info1;
		this.info2 = info2;
		this.info3 = info3;
		this.info4 = info4;
		this.infor5 = infor5;
		this.roomPca = roomPca;
		this.dbmsTime = dbmsTime;
	}

	// Property accessors

	public String getMeetingroomId() {
		return this.meetingroomId;
	}

	public void setMeetingroomId(String meetingroomId) {
		this.meetingroomId = meetingroomId;
	}

	public String getMeetingroomName() {
		return this.meetingroomName;
	}

	public void setMeetingroomName(String meetingroomName) {
		this.meetingroomName = meetingroomName;
	}

	public String getRoomNo() {
		return this.roomNo;
	}

	public void setRoomNo(String roomNo) {
		this.roomNo = roomNo;
	}

	public Integer getMeetingroomType() {
		return this.meetingroomType;
	}

	public void setMeetingroomType(Integer meetingroomType) {
		this.meetingroomType = meetingroomType;
	}

	public Integer getCapacity() {
		return this.capacity;
	}

	public void setCapacity(Integer capacity) {
		this.capacity = capacity;
	}

	public String getPlaneImg() {
		return this.planeImg;
	}

	public void setPlaneImg(String planeImg) {
		this.planeImg = planeImg;
	}

	public String getPictureImg() {
		return this.pictureImg;
	}

	public void setPictureImg(String pictureImg) {
		this.pictureImg = pictureImg;
	}

	public String getMeetingroomUrl() {
		return this.meetingroomUrl;
	}

	public void setMeetingroomUrl(String meetingroomUrl) {
		this.meetingroomUrl = meetingroomUrl;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getAdminId() {
		return this.adminId;
	}

	public void setAdminId(String adminId) {
		this.adminId = adminId;
	}

	public String getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}

	public String getAddressId() {
		return this.addressId;
	}

	public void setAddressId(String addressId) {
		this.addressId = addressId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Long getRevision() {
		return this.revision;
	}

	public void setRevision(Long revision) {
		this.revision = revision;
	}

	public String getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

	public String getInfo1() {
		return this.info1;
	}

	public void setInfo1(String info1) {
		this.info1 = info1;
	}

	public String getInfo2() {
		return this.info2;
	}

	public void setInfo2(String info2) {
		this.info2 = info2;
	}

	public String getInfo3() {
		return this.info3;
	}

	public void setInfo3(String info3) {
		this.info3 = info3;
	}

	public String getInfo4() {
		return this.info4;
	}

	public void setInfo4(String info4) {
		this.info4 = info4;
	}

	public String getInfor5() {
		return this.infor5;
	}

	public void setInfor5(String infor5) {
		this.infor5 = infor5;
	}

	public String getRoomPca() {
		return this.roomPca;
	}

	public void setRoomPca(String roomPca) {
		this.roomPca = roomPca;
	}

	public Date getDbmsTime() {
		return this.dbmsTime;
	}

	public void setDbmsTime(Date dbmsTime) {
		this.dbmsTime = dbmsTime;
	}

}