// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_MC3Operations.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.vmediax.oneplusn.ice.api.vmxICE;

public interface _MC3Operations
{
    CmdResult addTerminal(TerminalInfo ter, Ice.Current __current);

    CmdResult updateTerminal(TerminalInfo ter, Ice.Current __current);

    CmdResult deleteTerminal(String name, Ice.Current __current);

    java.util.List<TerminalInfo> getVedioTerminalList(Ice.Current __current);

    java.util.List<TerminalInfo> getAudioTerminalList(Ice.Current __current);

    java.util.List<TerminalTypeInfo> getTemplateTerminalTypeList(String name, Ice.Current __current);

    java.util.List<TerminalInfo> getTemplateH323TerminList(String templatename, Ice.Current __current);

    java.util.List<TerminalInfo> getTemplateH323IdleTerminList(String templatename, Ice.Current __current);

    java.util.List<TerminalInfo> getTemplateAudioTerminList(String templatename, Ice.Current __current);

    java.util.List<TerminalInfo> getTemplateAudioIdleTerminList(String templatename, Ice.Current __current);

    java.util.List<TemplateInfo> getTemplateList(Ice.Current __current);

    CmdResult addMutiTemplate(MutiTemplateInfo template, Ice.Current __current);

    CmdResult updateMutiTemplate(MutiTemplateInfo template, Ice.Current __current);

    CmdResult deleteMutiTemplate(String templateName, Ice.Current __current);

    java.util.List<LiveMeetTemplate> getLiveMeetTemplateList(Ice.Current __current);

    CmdResult addLiveMeetTemplate(LiveMeetTemplate template, Ice.Current __current);

    CmdResult updateLiveMeetTemplate(LiveMeetTemplate template, Ice.Current __current);

    CmdResult deleteLiveMeetTemplate(String templateName, Ice.Current __current);

    LiveMeetTemplate getLiveMeetTemplate(String templateName, Ice.Current __current);

    java.util.List<TemplateParamInfo> getTemplateParam(String templatename, Ice.Current __current);

    java.util.List<TerminalInfo> getConferenceTerminals(String meetnumber, Ice.Current __current);

    java.util.List<Conference> getConferenceList(Ice.Current __current);

    java.util.List<Conference> getConferenceInfo(String meetnumber, Ice.Current __current);

    java.util.List<ConferenceParam> getConferenceParam(String number, Ice.Current __current);

    int saveConferenceParam(String number, ConferenceParam cp, Ice.Current __current);

    java.util.List<TerminalInfo> getConferenceIdleVedioTerminals(String meetnumber, Ice.Current __current);

    java.util.List<TerminalInfo> getConferenceIdleAudioTerminals(String meetnumber, Ice.Current __current);

    java.util.List<Conference> getConferenceInfoByTerminal(TerminalInfo ter, Ice.Current __current);

    java.util.List<TerminalInfo> getAudioTerminal(String ternumber, Ice.Current __current);

    CmdResult startLiveMeet(String livetemplatename, java.util.List<TerminalInfo> vediotermList, java.util.List<TerminalInfo> audioTermList, Ice.Current __current);

    CmdResult startTemplateMeet(Conference conf, String template, Ice.Current __current);

    CmdResult stopMutiConference(String meetnumber, Ice.Current __current);

    CmdResult inviteVedioTerminal(java.util.List<TerminalInfo> terminalList, String qualityType, Conference conf, MutiTemplateInfo template, Ice.Current __current);

    CmdResult inviteAudioTerminal(java.util.List<TerminalInfo> terminalList, String meetnumber, Ice.Current __current);

    CmdResult kickMutiTerminal(String meetnumber, TerminalInfo ter, Ice.Current __current);

    CmdResult disconnectMutiTerminal(String meetnumber, TerminalInfo ter, Ice.Current __current);

    CmdResult connectMutiTerminal(String meetnumber, TerminalInfo ter, Ice.Current __current);

    CmdResult disconnectAll(String meetnumber, Ice.Current __current);

    CmdResult connectAll(String meetnumber, Ice.Current __current);

    CmdResult muteMutiSpeaker(String meetnumber, TerminalInfo terminal, String speaker, Ice.Current __current);

    CmdResult muteMutiMicrophone(String meetnumber, TerminalInfo terminal, String mic, Ice.Current __current);

    CmdResult muteAllMicrophone(String meetnumber, Ice.Current __current);

    CmdResult openAllMicrophone(String meetnumber, Ice.Current __current);

    CmdResult muteAllSpeaker(String meetnumber, Ice.Current __current);

    CmdResult openAllSpeaker(String meetnumber, Ice.Current __current);

    String getVscreen(String meetnumber, Ice.Current __current);

    java.util.List<ScreenInfo> getScreenInfo(String meetnumber, String vscreen, Ice.Current __current);

    CmdResult setScreen(java.util.List<TerminalInfo> terList, String number, String vscreen, String index, String mode, Ice.Current __current);

    int setQueue(String meetnumber, String index, TerminalInfo ter, Ice.Current __current);

    int setLecture(String meetnumber, TerminalInfo ter, String lecture, Ice.Current __current);

    int setChair(String meetnumber, TerminalInfo ter, String chair, Ice.Current __current);

    CmdResult setChairsee(String meetnumber, String mode, java.util.List<TerminalInfo> terminalList, Ice.Current __current);

    java.util.List<ChairCycleInfo> getChaircycleList(String meetnumber, Ice.Current __current);

    java.util.List<ChairCycleInfo> getChairseeList(String meetnumber, Ice.Current __current);

    int setFecc(String number, TerminalInfo ter, int actionType, Ice.Current __current);

    int stopFecc(String number, TerminalInfo ter, Ice.Current __current);

    int setQualityH323(String number, TerminalInfo ter, String bandwidth, String vsize, Ice.Current __current);

    int setQualitySoft(String number, TerminalInfo ter, String type, Ice.Current __current);

    CmdResult audioInsert(String ternumber1, String ternumberInsert, Ice.Current __current);

    CmdResult audioDismantle(String ternumber, Ice.Current __current);

    CmdResult audioHold(String terIp, Ice.Current __current);

    CmdResult audioUnHold(String terIp, Ice.Current __current);

    CmdResult audioTansfer(String ternumber, String targetnumber, Ice.Current __current);

    CmdResult audioStartSpy(String spyer, String ternumber, Ice.Current __current);

    CmdResult audioStopSpy(String spyer, Ice.Current __current);

    CmdResult audioStartRecord(String ternumber, Ice.Current __current);

    CmdResult audioStopRecord(String ternumber, Ice.Current __current);

    CmdResult powerPickUp(String num1, String targetnum, Ice.Current __current);

    CmdResult callback(String numa, String numb, Ice.Current __current);

    CmdResult consult(String conNum, String targetNum, Ice.Current __current);

    CmdResult meetShift(String meet1, String dstroomid, Ice.Current __current);

    CmdResult setAudioServ(String servip, String username, String pwd, Ice.Current __current);

    java.util.List<PacketInfo> getMemberPacketStatus(String meetnumber, Ice.Current __current);

    /**
     * add by penglong 20130114 gw start
     * @param __current The Current object for the invocation.
     **/
    CmdResult getServiceMode(Ice.Current __current);

    CmdResult getChannelsInLicenseNumber(Ice.Current __current);

    CmdResult setGWIP(String virtualFromIp, String virtualToIp, String subNetmask, Ice.Current __current);

    CmdResult setFixGWIP(String fixVirtualIp, String subNetmask, Ice.Current __current);

    CmdResult deleteGWIP(String virtualFromIp, String virtualToIp, Ice.Current __current);

    CmdResult deleteFixGWIP(String fixVirtualIp, Ice.Current __current);

    CmdResult clearAllGWIP(Ice.Current __current);

    CmdResult restartServer(Ice.Current __current);

    CmdResult startChannels(Conference channelsInfo, Ice.Current __current);

    CmdResult stopChannels(String channelsNumber, Ice.Current __current);

    java.util.List<Conference> getChannelsList(Ice.Current __current);

    CmdResult callH323Terminal2Channels(TerminalInfo h323Terminal, String number, Ice.Current __current);

    CmdResult disconnectH323Call2Channels(TerminalInfo h323Terminal, String number, Ice.Current __current);

    CmdResult reconnectH323Call2Channels(TerminalInfo h323Terminal, String number, Ice.Current __current);

    CmdResult stopH323Call2Channels(TerminalInfo h323Terminal, String number, Ice.Current __current);

    CmdResult callRtspTerminal2Channels(TerminalInfo rtspTerminal, String number, Ice.Current __current);

    CmdResult stopRtspCall2Channels(TerminalInfo rtspTerminal, String number, Ice.Current __current);

    CmdResult disconnectRtspCall2Channels(TerminalInfo rtspTerminal, String number, Ice.Current __current);

    CmdResult reconnectRtspCall2Channels(TerminalInfo rtspTerminal, String number, Ice.Current __current);

    CmdResult setLogoPath2Channels(String logoPath, Ice.Current __current);
}
