// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `MC2Prx.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.vmediax.oneplusn.ice.api.vmxICE;

public interface MC2Prx extends vmxICE.VMXObjectPrx
{
    public int addTerminal(String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc);

    public int addTerminal(String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addTerminal(String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc);

    public Ice.AsyncResult begin_addTerminal(String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addTerminal(String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, Ice.Callback __cb);

    public Ice.AsyncResult begin_addTerminal(String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_addTerminal(String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, Callback_MC2_addTerminal __cb);

    public Ice.AsyncResult begin_addTerminal(String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, java.util.Map<String, String> __ctx, Callback_MC2_addTerminal __cb);

    public int end_addTerminal(Ice.AsyncResult __result);

    public int addTerminalXML(String id, String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc);

    public int addTerminalXML(String id, String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addTerminalXML(String id, String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc);

    public Ice.AsyncResult begin_addTerminalXML(String id, String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addTerminalXML(String id, String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, Ice.Callback __cb);

    public Ice.AsyncResult begin_addTerminalXML(String id, String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_addTerminalXML(String id, String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, Callback_MC2_addTerminalXML __cb);

    public Ice.AsyncResult begin_addTerminalXML(String id, String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, java.util.Map<String, String> __ctx, Callback_MC2_addTerminalXML __cb);

    public int end_addTerminalXML(Ice.AsyncResult __result);

    public int updateTerminal(String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc);

    public int updateTerminal(String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_updateTerminal(String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc);

    public Ice.AsyncResult begin_updateTerminal(String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_updateTerminal(String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, Ice.Callback __cb);

    public Ice.AsyncResult begin_updateTerminal(String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_updateTerminal(String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, Callback_MC2_updateTerminal __cb);

    public Ice.AsyncResult begin_updateTerminal(String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, java.util.Map<String, String> __ctx, Callback_MC2_updateTerminal __cb);

    public int end_updateTerminal(Ice.AsyncResult __result);

    public int deleteTerminal(String id);

    public int deleteTerminal(String id, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_deleteTerminal(String id);

    public Ice.AsyncResult begin_deleteTerminal(String id, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_deleteTerminal(String id, Ice.Callback __cb);

    public Ice.AsyncResult begin_deleteTerminal(String id, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_deleteTerminal(String id, Callback_MC2_deleteTerminal __cb);

    public Ice.AsyncResult begin_deleteTerminal(String id, java.util.Map<String, String> __ctx, Callback_MC2_deleteTerminal __cb);

    public int end_deleteTerminal(Ice.AsyncResult __result);

    public java.util.List<TerminalInfo> getTerminList();

    public java.util.List<TerminalInfo> getTerminList(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getTerminList();

    public Ice.AsyncResult begin_getTerminList(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getTerminList(Ice.Callback __cb);

    public Ice.AsyncResult begin_getTerminList(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getTerminList(Callback_MC2_getTerminList __cb);

    public Ice.AsyncResult begin_getTerminList(java.util.Map<String, String> __ctx, Callback_MC2_getTerminList __cb);

    public java.util.List<TerminalInfo> end_getTerminList(Ice.AsyncResult __result);

    public java.util.List<TerminalInfo> queryTerminList(String condition);

    public java.util.List<TerminalInfo> queryTerminList(String condition, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_queryTerminList(String condition);

    public Ice.AsyncResult begin_queryTerminList(String condition, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_queryTerminList(String condition, Ice.Callback __cb);

    public Ice.AsyncResult begin_queryTerminList(String condition, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_queryTerminList(String condition, Callback_MC2_queryTerminList __cb);

    public Ice.AsyncResult begin_queryTerminList(String condition, java.util.Map<String, String> __ctx, Callback_MC2_queryTerminList __cb);

    public java.util.List<TerminalInfo> end_queryTerminList(Ice.AsyncResult __result);

    public java.util.List<TerminalInfo> queryNotConfTerminalList();

    public java.util.List<TerminalInfo> queryNotConfTerminalList(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_queryNotConfTerminalList();

    public Ice.AsyncResult begin_queryNotConfTerminalList(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_queryNotConfTerminalList(Ice.Callback __cb);

    public Ice.AsyncResult begin_queryNotConfTerminalList(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_queryNotConfTerminalList(Callback_MC2_queryNotConfTerminalList __cb);

    public Ice.AsyncResult begin_queryNotConfTerminalList(java.util.Map<String, String> __ctx, Callback_MC2_queryNotConfTerminalList __cb);

    public java.util.List<TerminalInfo> end_queryNotConfTerminalList(Ice.AsyncResult __result);

    public java.util.List<TerminalInfo> getMemberListByConference(String number);

    public java.util.List<TerminalInfo> getMemberListByConference(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getMemberListByConference(String number);

    public Ice.AsyncResult begin_getMemberListByConference(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getMemberListByConference(String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_getMemberListByConference(String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getMemberListByConference(String number, Callback_MC2_getMemberListByConference __cb);

    public Ice.AsyncResult begin_getMemberListByConference(String number, java.util.Map<String, String> __ctx, Callback_MC2_getMemberListByConference __cb);

    public java.util.List<TerminalInfo> end_getMemberListByConference(Ice.AsyncResult __result);

    public java.util.List<TerminalInfo> getConnectMembersByConference(String number);

    public java.util.List<TerminalInfo> getConnectMembersByConference(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getConnectMembersByConference(String number);

    public Ice.AsyncResult begin_getConnectMembersByConference(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getConnectMembersByConference(String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_getConnectMembersByConference(String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getConnectMembersByConference(String number, Callback_MC2_getConnectMembersByConference __cb);

    public Ice.AsyncResult begin_getConnectMembersByConference(String number, java.util.Map<String, String> __ctx, Callback_MC2_getConnectMembersByConference __cb);

    public java.util.List<TerminalInfo> end_getConnectMembersByConference(Ice.AsyncResult __result);

    public java.util.List<TerminalInfo> getMemberListByConfForFlex(String number);

    public java.util.List<TerminalInfo> getMemberListByConfForFlex(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getMemberListByConfForFlex(String number);

    public Ice.AsyncResult begin_getMemberListByConfForFlex(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getMemberListByConfForFlex(String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_getMemberListByConfForFlex(String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getMemberListByConfForFlex(String number, Callback_MC2_getMemberListByConfForFlex __cb);

    public Ice.AsyncResult begin_getMemberListByConfForFlex(String number, java.util.Map<String, String> __ctx, Callback_MC2_getMemberListByConfForFlex __cb);

    public java.util.List<TerminalInfo> end_getMemberListByConfForFlex(Ice.AsyncResult __result);

    public java.util.List<TerminalInfo> getTempTerminList(String name);

    public java.util.List<TerminalInfo> getTempTerminList(String name, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getTempTerminList(String name);

    public Ice.AsyncResult begin_getTempTerminList(String name, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getTempTerminList(String name, Ice.Callback __cb);

    public Ice.AsyncResult begin_getTempTerminList(String name, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getTempTerminList(String name, Callback_MC2_getTempTerminList __cb);

    public Ice.AsyncResult begin_getTempTerminList(String name, java.util.Map<String, String> __ctx, Callback_MC2_getTempTerminList __cb);

    public java.util.List<TerminalInfo> end_getTempTerminList(Ice.AsyncResult __result);

    public java.util.List<TerminalInfo> getTempTerminIdleList(String name);

    public java.util.List<TerminalInfo> getTempTerminIdleList(String name, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getTempTerminIdleList(String name);

    public Ice.AsyncResult begin_getTempTerminIdleList(String name, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getTempTerminIdleList(String name, Ice.Callback __cb);

    public Ice.AsyncResult begin_getTempTerminIdleList(String name, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getTempTerminIdleList(String name, Callback_MC2_getTempTerminIdleList __cb);

    public Ice.AsyncResult begin_getTempTerminIdleList(String name, java.util.Map<String, String> __ctx, Callback_MC2_getTempTerminIdleList __cb);

    public java.util.List<TerminalInfo> end_getTempTerminIdleList(Ice.AsyncResult __result);

    public java.util.List<TerminalTypeInfo> getTemplateTerminalTypeList(String name);

    public java.util.List<TerminalTypeInfo> getTemplateTerminalTypeList(String name, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getTemplateTerminalTypeList(String name);

    public Ice.AsyncResult begin_getTemplateTerminalTypeList(String name, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getTemplateTerminalTypeList(String name, Ice.Callback __cb);

    public Ice.AsyncResult begin_getTemplateTerminalTypeList(String name, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getTemplateTerminalTypeList(String name, Callback_MC2_getTemplateTerminalTypeList __cb);

    public Ice.AsyncResult begin_getTemplateTerminalTypeList(String name, java.util.Map<String, String> __ctx, Callback_MC2_getTemplateTerminalTypeList __cb);

    public java.util.List<TerminalTypeInfo> end_getTemplateTerminalTypeList(Ice.AsyncResult __result);

    public int addTemplate(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel);

    public int addTemplate(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addTemplate(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel);

    public Ice.AsyncResult begin_addTemplate(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addTemplate(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, Ice.Callback __cb);

    public Ice.AsyncResult begin_addTemplate(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_addTemplate(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, Callback_MC2_addTemplate __cb);

    public Ice.AsyncResult begin_addTemplate(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, java.util.Map<String, String> __ctx, Callback_MC2_addTemplate __cb);

    public int end_addTemplate(Ice.AsyncResult __result);

    public int addTemplateXML(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel);

    public int addTemplateXML(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addTemplateXML(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel);

    public Ice.AsyncResult begin_addTemplateXML(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addTemplateXML(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, Ice.Callback __cb);

    public Ice.AsyncResult begin_addTemplateXML(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_addTemplateXML(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, Callback_MC2_addTemplateXML __cb);

    public Ice.AsyncResult begin_addTemplateXML(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, java.util.Map<String, String> __ctx, Callback_MC2_addTemplateXML __cb);

    public int end_addTemplateXML(Ice.AsyncResult __result);

    public java.util.Map<java.lang.String, java.lang.String> getTerminalIdToIp();

    public java.util.Map<java.lang.String, java.lang.String> getTerminalIdToIp(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getTerminalIdToIp();

    public Ice.AsyncResult begin_getTerminalIdToIp(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getTerminalIdToIp(Ice.Callback __cb);

    public Ice.AsyncResult begin_getTerminalIdToIp(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getTerminalIdToIp(Callback_MC2_getTerminalIdToIp __cb);

    public Ice.AsyncResult begin_getTerminalIdToIp(java.util.Map<String, String> __ctx, Callback_MC2_getTerminalIdToIp __cb);

    public java.util.Map<java.lang.String, java.lang.String> end_getTerminalIdToIp(Ice.AsyncResult __result);

    public int updateTemplate(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel);

    public int updateTemplate(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_updateTemplate(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel);

    public Ice.AsyncResult begin_updateTemplate(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_updateTemplate(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, Ice.Callback __cb);

    public Ice.AsyncResult begin_updateTemplate(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_updateTemplate(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, Callback_MC2_updateTemplate __cb);

    public Ice.AsyncResult begin_updateTemplate(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, java.util.Map<String, String> __ctx, Callback_MC2_updateTemplate __cb);

    public int end_updateTemplate(Ice.AsyncResult __result);

    public int deleteTemplate(String name);

    public int deleteTemplate(String name, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_deleteTemplate(String name);

    public Ice.AsyncResult begin_deleteTemplate(String name, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_deleteTemplate(String name, Ice.Callback __cb);

    public Ice.AsyncResult begin_deleteTemplate(String name, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_deleteTemplate(String name, Callback_MC2_deleteTemplate __cb);

    public Ice.AsyncResult begin_deleteTemplate(String name, java.util.Map<String, String> __ctx, Callback_MC2_deleteTemplate __cb);

    public int end_deleteTemplate(Ice.AsyncResult __result);

    public java.util.List<TemplateInfo> getTemplateList();

    public java.util.List<TemplateInfo> getTemplateList(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getTemplateList();

    public Ice.AsyncResult begin_getTemplateList(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getTemplateList(Ice.Callback __cb);

    public Ice.AsyncResult begin_getTemplateList(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getTemplateList(Callback_MC2_getTemplateList __cb);

    public Ice.AsyncResult begin_getTemplateList(java.util.Map<String, String> __ctx, Callback_MC2_getTemplateList __cb);

    public java.util.List<TemplateInfo> end_getTemplateList(Ice.AsyncResult __result);

    public java.util.List<TemplateInfo> queryTemplateList(String condition);

    public java.util.List<TemplateInfo> queryTemplateList(String condition, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_queryTemplateList(String condition);

    public Ice.AsyncResult begin_queryTemplateList(String condition, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_queryTemplateList(String condition, Ice.Callback __cb);

    public Ice.AsyncResult begin_queryTemplateList(String condition, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_queryTemplateList(String condition, Callback_MC2_queryTemplateList __cb);

    public Ice.AsyncResult begin_queryTemplateList(String condition, java.util.Map<String, String> __ctx, Callback_MC2_queryTemplateList __cb);

    public java.util.List<TemplateInfo> end_queryTemplateList(Ice.AsyncResult __result);

    public int startConference(Conference conf, String templatename, StringListSHolder existsNumberClientNames);

    public int startConference(Conference conf, String templatename, StringListSHolder existsNumberClientNames, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_startConference(Conference conf, String templatename);

    public Ice.AsyncResult begin_startConference(Conference conf, String templatename, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_startConference(Conference conf, String templatename, Ice.Callback __cb);

    public Ice.AsyncResult begin_startConference(Conference conf, String templatename, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_startConference(Conference conf, String templatename, Callback_MC2_startConference __cb);

    public Ice.AsyncResult begin_startConference(Conference conf, String templatename, java.util.Map<String, String> __ctx, Callback_MC2_startConference __cb);

    public int end_startConference(StringListSHolder existsNumberClientNames, Ice.AsyncResult __result);

    public int stopConference(String number);

    public int stopConference(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopConference(String number);

    public Ice.AsyncResult begin_stopConference(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopConference(String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopConference(String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopConference(String number, Callback_MC2_stopConference __cb);

    public Ice.AsyncResult begin_stopConference(String number, java.util.Map<String, String> __ctx, Callback_MC2_stopConference __cb);

    public int end_stopConference(Ice.AsyncResult __result);

    public java.util.List<Conference> getConferenceList();

    public java.util.List<Conference> getConferenceList(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getConferenceList();

    public Ice.AsyncResult begin_getConferenceList(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getConferenceList(Ice.Callback __cb);

    public Ice.AsyncResult begin_getConferenceList(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getConferenceList(Callback_MC2_getConferenceList __cb);

    public Ice.AsyncResult begin_getConferenceList(java.util.Map<String, String> __ctx, Callback_MC2_getConferenceList __cb);

    public java.util.List<Conference> end_getConferenceList(Ice.AsyncResult __result);

    public java.util.List<Conference> getConferenceInfo(String number);

    public java.util.List<Conference> getConferenceInfo(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getConferenceInfo(String number);

    public Ice.AsyncResult begin_getConferenceInfo(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getConferenceInfo(String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_getConferenceInfo(String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getConferenceInfo(String number, Callback_MC2_getConferenceInfo __cb);

    public Ice.AsyncResult begin_getConferenceInfo(String number, java.util.Map<String, String> __ctx, Callback_MC2_getConferenceInfo __cb);

    public java.util.List<Conference> end_getConferenceInfo(Ice.AsyncResult __result);

    public int start323Call(String terminalIp, String terminalName, String terminalType, String number, String qualityType);

    public int start323Call(String terminalIp, String terminalName, String terminalType, String number, String qualityType, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_start323Call(String terminalIp, String terminalName, String terminalType, String number, String qualityType);

    public Ice.AsyncResult begin_start323Call(String terminalIp, String terminalName, String terminalType, String number, String qualityType, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_start323Call(String terminalIp, String terminalName, String terminalType, String number, String qualityType, Ice.Callback __cb);

    public Ice.AsyncResult begin_start323Call(String terminalIp, String terminalName, String terminalType, String number, String qualityType, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_start323Call(String terminalIp, String terminalName, String terminalType, String number, String qualityType, Callback_MC2_start323Call __cb);

    public Ice.AsyncResult begin_start323Call(String terminalIp, String terminalName, String terminalType, String number, String qualityType, java.util.Map<String, String> __ctx, Callback_MC2_start323Call __cb);

    public int end_start323Call(Ice.AsyncResult __result);

    public int batchStart323Call(java.util.List<java.lang.String> terminalIpList, java.util.List<java.lang.String> terminalNameList, String number, String qualityType, StringListSHolder existTerminalNameList);

    public int batchStart323Call(java.util.List<java.lang.String> terminalIpList, java.util.List<java.lang.String> terminalNameList, String number, String qualityType, StringListSHolder existTerminalNameList, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_batchStart323Call(java.util.List<java.lang.String> terminalIpList, java.util.List<java.lang.String> terminalNameList, String number, String qualityType);

    public Ice.AsyncResult begin_batchStart323Call(java.util.List<java.lang.String> terminalIpList, java.util.List<java.lang.String> terminalNameList, String number, String qualityType, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_batchStart323Call(java.util.List<java.lang.String> terminalIpList, java.util.List<java.lang.String> terminalNameList, String number, String qualityType, Ice.Callback __cb);

    public Ice.AsyncResult begin_batchStart323Call(java.util.List<java.lang.String> terminalIpList, java.util.List<java.lang.String> terminalNameList, String number, String qualityType, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_batchStart323Call(java.util.List<java.lang.String> terminalIpList, java.util.List<java.lang.String> terminalNameList, String number, String qualityType, Callback_MC2_batchStart323Call __cb);

    public Ice.AsyncResult begin_batchStart323Call(java.util.List<java.lang.String> terminalIpList, java.util.List<java.lang.String> terminalNameList, String number, String qualityType, java.util.Map<String, String> __ctx, Callback_MC2_batchStart323Call __cb);

    public int end_batchStart323Call(StringListSHolder existTerminalNameList, Ice.AsyncResult __result);

    public int stop323Call(String terminalIp, String number);

    public int stop323Call(String terminalIp, String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stop323Call(String terminalIp, String number);

    public Ice.AsyncResult begin_stop323Call(String terminalIp, String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stop323Call(String terminalIp, String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_stop323Call(String terminalIp, String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_stop323Call(String terminalIp, String number, Callback_MC2_stop323Call __cb);

    public Ice.AsyncResult begin_stop323Call(String terminalIp, String number, java.util.Map<String, String> __ctx, Callback_MC2_stop323Call __cb);

    public int end_stop323Call(Ice.AsyncResult __result);

    public int disconnect323Call(String terminalIp, String number);

    public int disconnect323Call(String terminalIp, String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_disconnect323Call(String terminalIp, String number);

    public Ice.AsyncResult begin_disconnect323Call(String terminalIp, String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_disconnect323Call(String terminalIp, String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_disconnect323Call(String terminalIp, String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_disconnect323Call(String terminalIp, String number, Callback_MC2_disconnect323Call __cb);

    public Ice.AsyncResult begin_disconnect323Call(String terminalIp, String number, java.util.Map<String, String> __ctx, Callback_MC2_disconnect323Call __cb);

    public int end_disconnect323Call(Ice.AsyncResult __result);

    public int connect323Call(String terminalIp, String terminalName, String number);

    public int connect323Call(String terminalIp, String terminalName, String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_connect323Call(String terminalIp, String terminalName, String number);

    public Ice.AsyncResult begin_connect323Call(String terminalIp, String terminalName, String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_connect323Call(String terminalIp, String terminalName, String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_connect323Call(String terminalIp, String terminalName, String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_connect323Call(String terminalIp, String terminalName, String number, Callback_MC2_connect323Call __cb);

    public Ice.AsyncResult begin_connect323Call(String terminalIp, String terminalName, String number, java.util.Map<String, String> __ctx, Callback_MC2_connect323Call __cb);

    public int end_connect323Call(Ice.AsyncResult __result);

    public int stopSoftCall(String terminalName, String number);

    public int stopSoftCall(String terminalName, String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopSoftCall(String terminalName, String number);

    public Ice.AsyncResult begin_stopSoftCall(String terminalName, String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopSoftCall(String terminalName, String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopSoftCall(String terminalName, String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopSoftCall(String terminalName, String number, Callback_MC2_stopSoftCall __cb);

    public Ice.AsyncResult begin_stopSoftCall(String terminalName, String number, java.util.Map<String, String> __ctx, Callback_MC2_stopSoftCall __cb);

    public int end_stopSoftCall(Ice.AsyncResult __result);

    public int stopMobileCall(String terminalName, String number);

    public int stopMobileCall(String terminalName, String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopMobileCall(String terminalName, String number);

    public Ice.AsyncResult begin_stopMobileCall(String terminalName, String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopMobileCall(String terminalName, String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopMobileCall(String terminalName, String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopMobileCall(String terminalName, String number, Callback_MC2_stopMobileCall __cb);

    public Ice.AsyncResult begin_stopMobileCall(String terminalName, String number, java.util.Map<String, String> __ctx, Callback_MC2_stopMobileCall __cb);

    public int end_stopMobileCall(Ice.AsyncResult __result);

    public int disconnectAll(String number);

    public int disconnectAll(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_disconnectAll(String number);

    public Ice.AsyncResult begin_disconnectAll(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_disconnectAll(String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_disconnectAll(String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_disconnectAll(String number, Callback_MC2_disconnectAll __cb);

    public Ice.AsyncResult begin_disconnectAll(String number, java.util.Map<String, String> __ctx, Callback_MC2_disconnectAll __cb);

    public int end_disconnectAll(Ice.AsyncResult __result);

    public int connectAll(String number);

    public int connectAll(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_connectAll(String number);

    public Ice.AsyncResult begin_connectAll(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_connectAll(String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_connectAll(String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_connectAll(String number, Callback_MC2_connectAll __cb);

    public Ice.AsyncResult begin_connectAll(String number, java.util.Map<String, String> __ctx, Callback_MC2_connectAll __cb);

    public int end_connectAll(Ice.AsyncResult __result);

    public int muteMicrophone(String number, String terminal, String mic);

    public int muteMicrophone(String number, String terminal, String mic, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_muteMicrophone(String number, String terminal, String mic);

    public Ice.AsyncResult begin_muteMicrophone(String number, String terminal, String mic, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_muteMicrophone(String number, String terminal, String mic, Ice.Callback __cb);

    public Ice.AsyncResult begin_muteMicrophone(String number, String terminal, String mic, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_muteMicrophone(String number, String terminal, String mic, Callback_MC2_muteMicrophone __cb);

    public Ice.AsyncResult begin_muteMicrophone(String number, String terminal, String mic, java.util.Map<String, String> __ctx, Callback_MC2_muteMicrophone __cb);

    public int end_muteMicrophone(Ice.AsyncResult __result);

    public int muteSpeaker(String number, String terminal, String speaker);

    public int muteSpeaker(String number, String terminal, String speaker, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_muteSpeaker(String number, String terminal, String speaker);

    public Ice.AsyncResult begin_muteSpeaker(String number, String terminal, String speaker, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_muteSpeaker(String number, String terminal, String speaker, Ice.Callback __cb);

    public Ice.AsyncResult begin_muteSpeaker(String number, String terminal, String speaker, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_muteSpeaker(String number, String terminal, String speaker, Callback_MC2_muteSpeaker __cb);

    public Ice.AsyncResult begin_muteSpeaker(String number, String terminal, String speaker, java.util.Map<String, String> __ctx, Callback_MC2_muteSpeaker __cb);

    public int end_muteSpeaker(Ice.AsyncResult __result);

    public int muteAllMicrophone(String number);

    public int muteAllMicrophone(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_muteAllMicrophone(String number);

    public Ice.AsyncResult begin_muteAllMicrophone(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_muteAllMicrophone(String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_muteAllMicrophone(String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_muteAllMicrophone(String number, Callback_MC2_muteAllMicrophone __cb);

    public Ice.AsyncResult begin_muteAllMicrophone(String number, java.util.Map<String, String> __ctx, Callback_MC2_muteAllMicrophone __cb);

    public int end_muteAllMicrophone(Ice.AsyncResult __result);

    public int openAllMicrophone(String number);

    public int openAllMicrophone(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_openAllMicrophone(String number);

    public Ice.AsyncResult begin_openAllMicrophone(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_openAllMicrophone(String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_openAllMicrophone(String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_openAllMicrophone(String number, Callback_MC2_openAllMicrophone __cb);

    public Ice.AsyncResult begin_openAllMicrophone(String number, java.util.Map<String, String> __ctx, Callback_MC2_openAllMicrophone __cb);

    public int end_openAllMicrophone(Ice.AsyncResult __result);

    public int muteAllSpeaker(String number);

    public int muteAllSpeaker(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_muteAllSpeaker(String number);

    public Ice.AsyncResult begin_muteAllSpeaker(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_muteAllSpeaker(String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_muteAllSpeaker(String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_muteAllSpeaker(String number, Callback_MC2_muteAllSpeaker __cb);

    public Ice.AsyncResult begin_muteAllSpeaker(String number, java.util.Map<String, String> __ctx, Callback_MC2_muteAllSpeaker __cb);

    public int end_muteAllSpeaker(Ice.AsyncResult __result);

    public int openAllSpeaker(String number);

    public int openAllSpeaker(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_openAllSpeaker(String number);

    public Ice.AsyncResult begin_openAllSpeaker(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_openAllSpeaker(String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_openAllSpeaker(String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_openAllSpeaker(String number, Callback_MC2_openAllSpeaker __cb);

    public Ice.AsyncResult begin_openAllSpeaker(String number, java.util.Map<String, String> __ctx, Callback_MC2_openAllSpeaker __cb);

    public int end_openAllSpeaker(Ice.AsyncResult __result);

    public String getVscreen(String number);

    public String getVscreen(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getVscreen(String number);

    public Ice.AsyncResult begin_getVscreen(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getVscreen(String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_getVscreen(String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getVscreen(String number, Callback_MC2_getVscreen __cb);

    public Ice.AsyncResult begin_getVscreen(String number, java.util.Map<String, String> __ctx, Callback_MC2_getVscreen __cb);

    public String end_getVscreen(Ice.AsyncResult __result);

    public java.util.List<ScreenInfo> getScreenInfo(String number, String vscreen);

    public java.util.List<ScreenInfo> getScreenInfo(String number, String vscreen, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getScreenInfo(String number, String vscreen);

    public Ice.AsyncResult begin_getScreenInfo(String number, String vscreen, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getScreenInfo(String number, String vscreen, Ice.Callback __cb);

    public Ice.AsyncResult begin_getScreenInfo(String number, String vscreen, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getScreenInfo(String number, String vscreen, Callback_MC2_getScreenInfo __cb);

    public Ice.AsyncResult begin_getScreenInfo(String number, String vscreen, java.util.Map<String, String> __ctx, Callback_MC2_getScreenInfo __cb);

    public java.util.List<ScreenInfo> end_getScreenInfo(Ice.AsyncResult __result);

    public int setScreen(java.util.List<java.lang.String> terminalIp, java.util.List<java.lang.String> terminalName, String number, String vscreen, String index, String mode);

    public int setScreen(java.util.List<java.lang.String> terminalIp, java.util.List<java.lang.String> terminalName, String number, String vscreen, String index, String mode, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setScreen(java.util.List<java.lang.String> terminalIp, java.util.List<java.lang.String> terminalName, String number, String vscreen, String index, String mode);

    public Ice.AsyncResult begin_setScreen(java.util.List<java.lang.String> terminalIp, java.util.List<java.lang.String> terminalName, String number, String vscreen, String index, String mode, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setScreen(java.util.List<java.lang.String> terminalIp, java.util.List<java.lang.String> terminalName, String number, String vscreen, String index, String mode, Ice.Callback __cb);

    public Ice.AsyncResult begin_setScreen(java.util.List<java.lang.String> terminalIp, java.util.List<java.lang.String> terminalName, String number, String vscreen, String index, String mode, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_setScreen(java.util.List<java.lang.String> terminalIp, java.util.List<java.lang.String> terminalName, String number, String vscreen, String index, String mode, Callback_MC2_setScreen __cb);

    public Ice.AsyncResult begin_setScreen(java.util.List<java.lang.String> terminalIp, java.util.List<java.lang.String> terminalName, String number, String vscreen, String index, String mode, java.util.Map<String, String> __ctx, Callback_MC2_setScreen __cb);

    public int end_setScreen(Ice.AsyncResult __result);

    public int setSubscreenMode(String number, String index, String mode);

    public int setSubscreenMode(String number, String index, String mode, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setSubscreenMode(String number, String index, String mode);

    public Ice.AsyncResult begin_setSubscreenMode(String number, String index, String mode, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setSubscreenMode(String number, String index, String mode, Ice.Callback __cb);

    public Ice.AsyncResult begin_setSubscreenMode(String number, String index, String mode, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_setSubscreenMode(String number, String index, String mode, Callback_MC2_setSubscreenMode __cb);

    public Ice.AsyncResult begin_setSubscreenMode(String number, String index, String mode, java.util.Map<String, String> __ctx, Callback_MC2_setSubscreenMode __cb);

    public int end_setSubscreenMode(Ice.AsyncResult __result);

    public int setQueue(String number, String index, String state);

    public int setQueue(String number, String index, String state, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setQueue(String number, String index, String state);

    public Ice.AsyncResult begin_setQueue(String number, String index, String state, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setQueue(String number, String index, String state, Ice.Callback __cb);

    public Ice.AsyncResult begin_setQueue(String number, String index, String state, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_setQueue(String number, String index, String state, Callback_MC2_setQueue __cb);

    public Ice.AsyncResult begin_setQueue(String number, String index, String state, java.util.Map<String, String> __ctx, Callback_MC2_setQueue __cb);

    public int end_setQueue(Ice.AsyncResult __result);

    public int saveConferenceParam(String number, ConferenceParam cp);

    public int saveConferenceParam(String number, ConferenceParam cp, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_saveConferenceParam(String number, ConferenceParam cp);

    public Ice.AsyncResult begin_saveConferenceParam(String number, ConferenceParam cp, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_saveConferenceParam(String number, ConferenceParam cp, Ice.Callback __cb);

    public Ice.AsyncResult begin_saveConferenceParam(String number, ConferenceParam cp, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_saveConferenceParam(String number, ConferenceParam cp, Callback_MC2_saveConferenceParam __cb);

    public Ice.AsyncResult begin_saveConferenceParam(String number, ConferenceParam cp, java.util.Map<String, String> __ctx, Callback_MC2_saveConferenceParam __cb);

    public int end_saveConferenceParam(Ice.AsyncResult __result);

    public java.util.List<ConferenceParam> getConferenceParam(String number);

    public java.util.List<ConferenceParam> getConferenceParam(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getConferenceParam(String number);

    public Ice.AsyncResult begin_getConferenceParam(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getConferenceParam(String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_getConferenceParam(String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getConferenceParam(String number, Callback_MC2_getConferenceParam __cb);

    public Ice.AsyncResult begin_getConferenceParam(String number, java.util.Map<String, String> __ctx, Callback_MC2_getConferenceParam __cb);

    public java.util.List<ConferenceParam> end_getConferenceParam(Ice.AsyncResult __result);

    public int saveTemplateParam(TemplateParamInfo tp);

    public int saveTemplateParam(TemplateParamInfo tp, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_saveTemplateParam(TemplateParamInfo tp);

    public Ice.AsyncResult begin_saveTemplateParam(TemplateParamInfo tp, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_saveTemplateParam(TemplateParamInfo tp, Ice.Callback __cb);

    public Ice.AsyncResult begin_saveTemplateParam(TemplateParamInfo tp, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_saveTemplateParam(TemplateParamInfo tp, Callback_MC2_saveTemplateParam __cb);

    public Ice.AsyncResult begin_saveTemplateParam(TemplateParamInfo tp, java.util.Map<String, String> __ctx, Callback_MC2_saveTemplateParam __cb);

    public int end_saveTemplateParam(Ice.AsyncResult __result);

    public java.util.List<TemplateParamInfo> getTemplateParam(String templatename);

    public java.util.List<TemplateParamInfo> getTemplateParam(String templatename, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getTemplateParam(String templatename);

    public Ice.AsyncResult begin_getTemplateParam(String templatename, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getTemplateParam(String templatename, Ice.Callback __cb);

    public Ice.AsyncResult begin_getTemplateParam(String templatename, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getTemplateParam(String templatename, Callback_MC2_getTemplateParam __cb);

    public Ice.AsyncResult begin_getTemplateParam(String templatename, java.util.Map<String, String> __ctx, Callback_MC2_getTemplateParam __cb);

    public java.util.List<TemplateParamInfo> end_getTemplateParam(Ice.AsyncResult __result);

    public String validateName(String name, String confId);

    public String validateName(String name, String confId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_validateName(String name, String confId);

    public Ice.AsyncResult begin_validateName(String name, String confId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_validateName(String name, String confId, Ice.Callback __cb);

    public Ice.AsyncResult begin_validateName(String name, String confId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_validateName(String name, String confId, Callback_MC2_validateName __cb);

    public Ice.AsyncResult begin_validateName(String name, String confId, java.util.Map<String, String> __ctx, Callback_MC2_validateName __cb);

    public String end_validateName(Ice.AsyncResult __result);

    public int setLecture(String number, String terminalIp, String terminalName, String lecture);

    public int setLecture(String number, String terminalIp, String terminalName, String lecture, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setLecture(String number, String terminalIp, String terminalName, String lecture);

    public Ice.AsyncResult begin_setLecture(String number, String terminalIp, String terminalName, String lecture, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setLecture(String number, String terminalIp, String terminalName, String lecture, Ice.Callback __cb);

    public Ice.AsyncResult begin_setLecture(String number, String terminalIp, String terminalName, String lecture, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_setLecture(String number, String terminalIp, String terminalName, String lecture, Callback_MC2_setLecture __cb);

    public Ice.AsyncResult begin_setLecture(String number, String terminalIp, String terminalName, String lecture, java.util.Map<String, String> __ctx, Callback_MC2_setLecture __cb);

    public int end_setLecture(Ice.AsyncResult __result);

    public int setChair(String number, String terminalIp, String chair);

    public int setChair(String number, String terminalIp, String chair, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setChair(String number, String terminalIp, String chair);

    public Ice.AsyncResult begin_setChair(String number, String terminalIp, String chair, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setChair(String number, String terminalIp, String chair, Ice.Callback __cb);

    public Ice.AsyncResult begin_setChair(String number, String terminalIp, String chair, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_setChair(String number, String terminalIp, String chair, Callback_MC2_setChair __cb);

    public Ice.AsyncResult begin_setChair(String number, String terminalIp, String chair, java.util.Map<String, String> __ctx, Callback_MC2_setChair __cb);

    public int end_setChair(Ice.AsyncResult __result);

    public int setChairsee(String number, String mode, String[] terminalIp, String[] terminalName);

    public int setChairsee(String number, String mode, String[] terminalIp, String[] terminalName, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setChairsee(String number, String mode, String[] terminalIp, String[] terminalName);

    public Ice.AsyncResult begin_setChairsee(String number, String mode, String[] terminalIp, String[] terminalName, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setChairsee(String number, String mode, String[] terminalIp, String[] terminalName, Ice.Callback __cb);

    public Ice.AsyncResult begin_setChairsee(String number, String mode, String[] terminalIp, String[] terminalName, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_setChairsee(String number, String mode, String[] terminalIp, String[] terminalName, Callback_MC2_setChairsee __cb);

    public Ice.AsyncResult begin_setChairsee(String number, String mode, String[] terminalIp, String[] terminalName, java.util.Map<String, String> __ctx, Callback_MC2_setChairsee __cb);

    public int end_setChairsee(Ice.AsyncResult __result);

    public java.util.List<ChairCycleInfo> getChaircycleList(String number);

    public java.util.List<ChairCycleInfo> getChaircycleList(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getChaircycleList(String number);

    public Ice.AsyncResult begin_getChaircycleList(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getChaircycleList(String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_getChaircycleList(String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getChaircycleList(String number, Callback_MC2_getChaircycleList __cb);

    public Ice.AsyncResult begin_getChaircycleList(String number, java.util.Map<String, String> __ctx, Callback_MC2_getChaircycleList __cb);

    public java.util.List<ChairCycleInfo> end_getChaircycleList(Ice.AsyncResult __result);

    public java.util.List<ChairCycleInfo> getChairCycleChoiceTerminals(String number);

    public java.util.List<ChairCycleInfo> getChairCycleChoiceTerminals(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getChairCycleChoiceTerminals(String number);

    public Ice.AsyncResult begin_getChairCycleChoiceTerminals(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getChairCycleChoiceTerminals(String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_getChairCycleChoiceTerminals(String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getChairCycleChoiceTerminals(String number, Callback_MC2_getChairCycleChoiceTerminals __cb);

    public Ice.AsyncResult begin_getChairCycleChoiceTerminals(String number, java.util.Map<String, String> __ctx, Callback_MC2_getChairCycleChoiceTerminals __cb);

    public java.util.List<ChairCycleInfo> end_getChairCycleChoiceTerminals(Ice.AsyncResult __result);

    public java.util.List<ChairCycleInfo> getChairseeList(String number);

    public java.util.List<ChairCycleInfo> getChairseeList(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getChairseeList(String number);

    public Ice.AsyncResult begin_getChairseeList(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getChairseeList(String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_getChairseeList(String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getChairseeList(String number, Callback_MC2_getChairseeList __cb);

    public Ice.AsyncResult begin_getChairseeList(String number, java.util.Map<String, String> __ctx, Callback_MC2_getChairseeList __cb);

    public java.util.List<ChairCycleInfo> end_getChairseeList(Ice.AsyncResult __result);

    public int setFecc(String number, String terminalIp, int actionType);

    public int setFecc(String number, String terminalIp, int actionType, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setFecc(String number, String terminalIp, int actionType);

    public Ice.AsyncResult begin_setFecc(String number, String terminalIp, int actionType, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setFecc(String number, String terminalIp, int actionType, Ice.Callback __cb);

    public Ice.AsyncResult begin_setFecc(String number, String terminalIp, int actionType, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_setFecc(String number, String terminalIp, int actionType, Callback_MC2_setFecc __cb);

    public Ice.AsyncResult begin_setFecc(String number, String terminalIp, int actionType, java.util.Map<String, String> __ctx, Callback_MC2_setFecc __cb);

    public int end_setFecc(Ice.AsyncResult __result);

    public int stopFecc(String number, String terminalIp);

    public int stopFecc(String number, String terminalIp, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopFecc(String number, String terminalIp);

    public Ice.AsyncResult begin_stopFecc(String number, String terminalIp, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopFecc(String number, String terminalIp, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopFecc(String number, String terminalIp, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopFecc(String number, String terminalIp, Callback_MC2_stopFecc __cb);

    public Ice.AsyncResult begin_stopFecc(String number, String terminalIp, java.util.Map<String, String> __ctx, Callback_MC2_stopFecc __cb);

    public int end_stopFecc(Ice.AsyncResult __result);

    public int setQualityH323(String number, String terminalIp, String bandwidth, String vsize);

    public int setQualityH323(String number, String terminalIp, String bandwidth, String vsize, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setQualityH323(String number, String terminalIp, String bandwidth, String vsize);

    public Ice.AsyncResult begin_setQualityH323(String number, String terminalIp, String bandwidth, String vsize, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setQualityH323(String number, String terminalIp, String bandwidth, String vsize, Ice.Callback __cb);

    public Ice.AsyncResult begin_setQualityH323(String number, String terminalIp, String bandwidth, String vsize, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_setQualityH323(String number, String terminalIp, String bandwidth, String vsize, Callback_MC2_setQualityH323 __cb);

    public Ice.AsyncResult begin_setQualityH323(String number, String terminalIp, String bandwidth, String vsize, java.util.Map<String, String> __ctx, Callback_MC2_setQualityH323 __cb);

    public int end_setQualityH323(Ice.AsyncResult __result);

    public int setQualitySoft(String number, String terminalIp, String type);

    public int setQualitySoft(String number, String terminalIp, String type, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setQualitySoft(String number, String terminalIp, String type);

    public Ice.AsyncResult begin_setQualitySoft(String number, String terminalIp, String type, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setQualitySoft(String number, String terminalIp, String type, Ice.Callback __cb);

    public Ice.AsyncResult begin_setQualitySoft(String number, String terminalIp, String type, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_setQualitySoft(String number, String terminalIp, String type, Callback_MC2_setQualitySoft __cb);

    public Ice.AsyncResult begin_setQualitySoft(String number, String terminalIp, String type, java.util.Map<String, String> __ctx, Callback_MC2_setQualitySoft __cb);

    public int end_setQualitySoft(Ice.AsyncResult __result);

    public int saveSysConfig(SysConfig sys);

    public int saveSysConfig(SysConfig sys, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_saveSysConfig(SysConfig sys);

    public Ice.AsyncResult begin_saveSysConfig(SysConfig sys, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_saveSysConfig(SysConfig sys, Ice.Callback __cb);

    public Ice.AsyncResult begin_saveSysConfig(SysConfig sys, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_saveSysConfig(SysConfig sys, Callback_MC2_saveSysConfig __cb);

    public Ice.AsyncResult begin_saveSysConfig(SysConfig sys, java.util.Map<String, String> __ctx, Callback_MC2_saveSysConfig __cb);

    public int end_saveSysConfig(Ice.AsyncResult __result);

    public java.util.List<SysConfig> getSysConfig();

    public java.util.List<SysConfig> getSysConfig(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getSysConfig();

    public Ice.AsyncResult begin_getSysConfig(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getSysConfig(Ice.Callback __cb);

    public Ice.AsyncResult begin_getSysConfig(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getSysConfig(Callback_MC2_getSysConfig __cb);

    public Ice.AsyncResult begin_getSysConfig(java.util.Map<String, String> __ctx, Callback_MC2_getSysConfig __cb);

    public java.util.List<SysConfig> end_getSysConfig(Ice.AsyncResult __result);

    public java.util.List<IConfig> getIConfig();

    public java.util.List<IConfig> getIConfig(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getIConfig();

    public Ice.AsyncResult begin_getIConfig(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getIConfig(Ice.Callback __cb);

    public Ice.AsyncResult begin_getIConfig(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getIConfig(Callback_MC2_getIConfig __cb);

    public Ice.AsyncResult begin_getIConfig(java.util.Map<String, String> __ctx, Callback_MC2_getIConfig __cb);

    public java.util.List<IConfig> end_getIConfig(Ice.AsyncResult __result);

    public int setIConfig(String name, String value);

    public int setIConfig(String name, String value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setIConfig(String name, String value);

    public Ice.AsyncResult begin_setIConfig(String name, String value, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setIConfig(String name, String value, Ice.Callback __cb);

    public Ice.AsyncResult begin_setIConfig(String name, String value, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_setIConfig(String name, String value, Callback_MC2_setIConfig __cb);

    public Ice.AsyncResult begin_setIConfig(String name, String value, java.util.Map<String, String> __ctx, Callback_MC2_setIConfig __cb);

    public int end_setIConfig(Ice.AsyncResult __result);

    public int startConferenceP2p();

    public int startConferenceP2p(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_startConferenceP2p();

    public Ice.AsyncResult begin_startConferenceP2p(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_startConferenceP2p(Ice.Callback __cb);

    public Ice.AsyncResult begin_startConferenceP2p(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_startConferenceP2p(Callback_MC2_startConferenceP2p __cb);

    public Ice.AsyncResult begin_startConferenceP2p(java.util.Map<String, String> __ctx, Callback_MC2_startConferenceP2p __cb);

    public int end_startConferenceP2p(Ice.AsyncResult __result);

    public int stopConferenceP2p(String number);

    public int stopConferenceP2p(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopConferenceP2p(String number);

    public Ice.AsyncResult begin_stopConferenceP2p(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopConferenceP2p(String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopConferenceP2p(String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopConferenceP2p(String number, Callback_MC2_stopConferenceP2p __cb);

    public Ice.AsyncResult begin_stopConferenceP2p(String number, java.util.Map<String, String> __ctx, Callback_MC2_stopConferenceP2p __cb);

    public int end_stopConferenceP2p(Ice.AsyncResult __result);

    public java.util.List<PacketInfo> getMemberPacketStatus(String number);

    public java.util.List<PacketInfo> getMemberPacketStatus(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getMemberPacketStatus(String number);

    public Ice.AsyncResult begin_getMemberPacketStatus(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getMemberPacketStatus(String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_getMemberPacketStatus(String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getMemberPacketStatus(String number, Callback_MC2_getMemberPacketStatus __cb);

    public Ice.AsyncResult begin_getMemberPacketStatus(String number, java.util.Map<String, String> __ctx, Callback_MC2_getMemberPacketStatus __cb);

    public java.util.List<PacketInfo> end_getMemberPacketStatus(Ice.AsyncResult __result);

    public int setExt(String number, String terminalIp, String ext);

    public int setExt(String number, String terminalIp, String ext, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setExt(String number, String terminalIp, String ext);

    public Ice.AsyncResult begin_setExt(String number, String terminalIp, String ext, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setExt(String number, String terminalIp, String ext, Ice.Callback __cb);

    public Ice.AsyncResult begin_setExt(String number, String terminalIp, String ext, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_setExt(String number, String terminalIp, String ext, Callback_MC2_setExt __cb);

    public Ice.AsyncResult begin_setExt(String number, String terminalIp, String ext, java.util.Map<String, String> __ctx, Callback_MC2_setExt __cb);

    public int end_setExt(Ice.AsyncResult __result);

    public int[] getClientCache(String number);

    public int[] getClientCache(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getClientCache(String number);

    public Ice.AsyncResult begin_getClientCache(String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getClientCache(String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_getClientCache(String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getClientCache(String number, Callback_MC2_getClientCache __cb);

    public Ice.AsyncResult begin_getClientCache(String number, java.util.Map<String, String> __ctx, Callback_MC2_getClientCache __cb);

    public int[] end_getClientCache(Ice.AsyncResult __result);

    public LicenseInfo getLicense();

    public LicenseInfo getLicense(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLicense();

    public Ice.AsyncResult begin_getLicense(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLicense(Ice.Callback __cb);

    public Ice.AsyncResult begin_getLicense(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLicense(Callback_MC2_getLicense __cb);

    public Ice.AsyncResult begin_getLicense(java.util.Map<String, String> __ctx, Callback_MC2_getLicense __cb);

    public LicenseInfo end_getLicense(Ice.AsyncResult __result);

    public int setRequestIFrame(String clientIP, String stream, String cmd);

    public int setRequestIFrame(String clientIP, String stream, String cmd, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setRequestIFrame(String clientIP, String stream, String cmd);

    public Ice.AsyncResult begin_setRequestIFrame(String clientIP, String stream, String cmd, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setRequestIFrame(String clientIP, String stream, String cmd, Ice.Callback __cb);

    public Ice.AsyncResult begin_setRequestIFrame(String clientIP, String stream, String cmd, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_setRequestIFrame(String clientIP, String stream, String cmd, Callback_MC2_setRequestIFrame __cb);

    public Ice.AsyncResult begin_setRequestIFrame(String clientIP, String stream, String cmd, java.util.Map<String, String> __ctx, Callback_MC2_setRequestIFrame __cb);

    public int end_setRequestIFrame(Ice.AsyncResult __result);

    public int startRtspCall(String rtspName, String number);

    public int startRtspCall(String rtspName, String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_startRtspCall(String rtspName, String number);

    public Ice.AsyncResult begin_startRtspCall(String rtspName, String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_startRtspCall(String rtspName, String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_startRtspCall(String rtspName, String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_startRtspCall(String rtspName, String number, Callback_MC2_startRtspCall __cb);

    public Ice.AsyncResult begin_startRtspCall(String rtspName, String number, java.util.Map<String, String> __ctx, Callback_MC2_startRtspCall __cb);

    public int end_startRtspCall(Ice.AsyncResult __result);

    public int stopRtspCall(String number, String rtspName);

    public int stopRtspCall(String number, String rtspName, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopRtspCall(String number, String rtspName);

    public Ice.AsyncResult begin_stopRtspCall(String number, String rtspName, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopRtspCall(String number, String rtspName, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopRtspCall(String number, String rtspName, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopRtspCall(String number, String rtspName, Callback_MC2_stopRtspCall __cb);

    public Ice.AsyncResult begin_stopRtspCall(String number, String rtspName, java.util.Map<String, String> __ctx, Callback_MC2_stopRtspCall __cb);

    public int end_stopRtspCall(Ice.AsyncResult __result);

    public int startSipCall(String sipIp, String number, String qualityType);

    public int startSipCall(String sipIp, String number, String qualityType, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_startSipCall(String sipIp, String number, String qualityType);

    public Ice.AsyncResult begin_startSipCall(String sipIp, String number, String qualityType, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_startSipCall(String sipIp, String number, String qualityType, Ice.Callback __cb);

    public Ice.AsyncResult begin_startSipCall(String sipIp, String number, String qualityType, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_startSipCall(String sipIp, String number, String qualityType, Callback_MC2_startSipCall __cb);

    public Ice.AsyncResult begin_startSipCall(String sipIp, String number, String qualityType, java.util.Map<String, String> __ctx, Callback_MC2_startSipCall __cb);

    public int end_startSipCall(Ice.AsyncResult __result);

    public int startSipCalled(String sipPhoneNumber, String number);

    public int startSipCalled(String sipPhoneNumber, String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_startSipCalled(String sipPhoneNumber, String number);

    public Ice.AsyncResult begin_startSipCalled(String sipPhoneNumber, String number, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_startSipCalled(String sipPhoneNumber, String number, Ice.Callback __cb);

    public Ice.AsyncResult begin_startSipCalled(String sipPhoneNumber, String number, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_startSipCalled(String sipPhoneNumber, String number, Callback_MC2_startSipCalled __cb);

    public Ice.AsyncResult begin_startSipCalled(String sipPhoneNumber, String number, java.util.Map<String, String> __ctx, Callback_MC2_startSipCalled __cb);

    public int end_startSipCalled(Ice.AsyncResult __result);

    public int stopSipCall(String number, String sipPhoneNumber);

    public int stopSipCall(String number, String sipPhoneNumber, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopSipCall(String number, String sipPhoneNumber);

    public Ice.AsyncResult begin_stopSipCall(String number, String sipPhoneNumber, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopSipCall(String number, String sipPhoneNumber, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopSipCall(String number, String sipPhoneNumber, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopSipCall(String number, String sipPhoneNumber, Callback_MC2_stopSipCall __cb);

    public Ice.AsyncResult begin_stopSipCall(String number, String sipPhoneNumber, java.util.Map<String, String> __ctx, Callback_MC2_stopSipCall __cb);

    public int end_stopSipCall(Ice.AsyncResult __result);

    public int registerServer(String clientIP, String userName, String password, String domain, String regServerIP, String authName);

    public int registerServer(String clientIP, String userName, String password, String domain, String regServerIP, String authName, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_registerServer(String clientIP, String userName, String password, String domain, String regServerIP, String authName);

    public Ice.AsyncResult begin_registerServer(String clientIP, String userName, String password, String domain, String regServerIP, String authName, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_registerServer(String clientIP, String userName, String password, String domain, String regServerIP, String authName, Ice.Callback __cb);

    public Ice.AsyncResult begin_registerServer(String clientIP, String userName, String password, String domain, String regServerIP, String authName, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_registerServer(String clientIP, String userName, String password, String domain, String regServerIP, String authName, Callback_MC2_registerServer __cb);

    public Ice.AsyncResult begin_registerServer(String clientIP, String userName, String password, String domain, String regServerIP, String authName, java.util.Map<String, String> __ctx, Callback_MC2_registerServer __cb);

    public int end_registerServer(Ice.AsyncResult __result);

    public int addSip(SipInfo sipTerminalInfo);

    public int addSip(SipInfo sipTerminalInfo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addSip(SipInfo sipTerminalInfo);

    public Ice.AsyncResult begin_addSip(SipInfo sipTerminalInfo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addSip(SipInfo sipTerminalInfo, Ice.Callback __cb);

    public Ice.AsyncResult begin_addSip(SipInfo sipTerminalInfo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_addSip(SipInfo sipTerminalInfo, Callback_MC2_addSip __cb);

    public Ice.AsyncResult begin_addSip(SipInfo sipTerminalInfo, java.util.Map<String, String> __ctx, Callback_MC2_addSip __cb);

    public int end_addSip(Ice.AsyncResult __result);

    public int updateSip(SipInfo sipTerminalInfo);

    public int updateSip(SipInfo sipTerminalInfo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_updateSip(SipInfo sipTerminalInfo);

    public Ice.AsyncResult begin_updateSip(SipInfo sipTerminalInfo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_updateSip(SipInfo sipTerminalInfo, Ice.Callback __cb);

    public Ice.AsyncResult begin_updateSip(SipInfo sipTerminalInfo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_updateSip(SipInfo sipTerminalInfo, Callback_MC2_updateSip __cb);

    public Ice.AsyncResult begin_updateSip(SipInfo sipTerminalInfo, java.util.Map<String, String> __ctx, Callback_MC2_updateSip __cb);

    public int end_updateSip(Ice.AsyncResult __result);

    public int deleteSip(String sipIp);

    public int deleteSip(String sipIp, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_deleteSip(String sipIp);

    public Ice.AsyncResult begin_deleteSip(String sipIp, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_deleteSip(String sipIp, Ice.Callback __cb);

    public Ice.AsyncResult begin_deleteSip(String sipIp, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_deleteSip(String sipIp, Callback_MC2_deleteSip __cb);

    public Ice.AsyncResult begin_deleteSip(String sipIp, java.util.Map<String, String> __ctx, Callback_MC2_deleteSip __cb);

    public int end_deleteSip(Ice.AsyncResult __result);

    public java.util.List<SipInfo> getSipList();

    public java.util.List<SipInfo> getSipList(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getSipList();

    public Ice.AsyncResult begin_getSipList(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getSipList(Ice.Callback __cb);

    public Ice.AsyncResult begin_getSipList(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getSipList(Callback_MC2_getSipList __cb);

    public Ice.AsyncResult begin_getSipList(java.util.Map<String, String> __ctx, Callback_MC2_getSipList __cb);

    public java.util.List<SipInfo> end_getSipList(Ice.AsyncResult __result);
}
