// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `TemplateParamInfo.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.vmediax.oneplusn.ice.api.vmxICE;

public class TemplateParamInfo implements java.lang.Cloneable, java.io.Serializable
{
    public String name;

    public String lecture;

    public String chair;

    public String chairsee;

    public String chaircycle;

    public String casecade;

    public String schedule;

    public String duration;

    public String date;

    public String time;

    public String week;

    public String monthday;

    public int autoConnectTimes;

    public String autoSound;

    public String meetName;

    public String delay;

    public String mnameFont;

    public String nameColor;

    public String useColor;

    public String mnameTop;

    public String nameBgColor;

    public String useWord;

    public String content;

    public String scrollSpeed;

    public String transparent;

    public String conftransparent;

    public String wordSize;

    public String wordLoction;

    public String fontBgColor;

    public String fontColor;

    public String poll;

    public String pwd;

    public String chpwd;

    public String audio;

    public String ext;

    public TemplateParamInfo()
    {
    }

    public TemplateParamInfo(String name, String lecture, String chair, String chairsee, String chaircycle, String casecade, String schedule, String duration, String date, String time, String week, String monthday, int autoConnectTimes, String autoSound, String meetName, String delay, String mnameFont, String nameColor, String useColor, String mnameTop, String nameBgColor, String useWord, String content, String scrollSpeed, String transparent, String conftransparent, String wordSize, String wordLoction, String fontBgColor, String fontColor, String poll, String pwd, String chpwd, String audio, String ext)
    {
        this.name = name;
        this.lecture = lecture;
        this.chair = chair;
        this.chairsee = chairsee;
        this.chaircycle = chaircycle;
        this.casecade = casecade;
        this.schedule = schedule;
        this.duration = duration;
        this.date = date;
        this.time = time;
        this.week = week;
        this.monthday = monthday;
        this.autoConnectTimes = autoConnectTimes;
        this.autoSound = autoSound;
        this.meetName = meetName;
        this.delay = delay;
        this.mnameFont = mnameFont;
        this.nameColor = nameColor;
        this.useColor = useColor;
        this.mnameTop = mnameTop;
        this.nameBgColor = nameBgColor;
        this.useWord = useWord;
        this.content = content;
        this.scrollSpeed = scrollSpeed;
        this.transparent = transparent;
        this.conftransparent = conftransparent;
        this.wordSize = wordSize;
        this.wordLoction = wordLoction;
        this.fontBgColor = fontBgColor;
        this.fontColor = fontColor;
        this.poll = poll;
        this.pwd = pwd;
        this.chpwd = chpwd;
        this.audio = audio;
        this.ext = ext;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        TemplateParamInfo _r = null;
        try
        {
            _r = (TemplateParamInfo)rhs;
        }
        catch(ClassCastException ex)
        {
        }

        if(_r != null)
        {
            if(name != _r.name)
            {
                if(name == null || _r.name == null || !name.equals(_r.name))
                {
                    return false;
                }
            }
            if(lecture != _r.lecture)
            {
                if(lecture == null || _r.lecture == null || !lecture.equals(_r.lecture))
                {
                    return false;
                }
            }
            if(chair != _r.chair)
            {
                if(chair == null || _r.chair == null || !chair.equals(_r.chair))
                {
                    return false;
                }
            }
            if(chairsee != _r.chairsee)
            {
                if(chairsee == null || _r.chairsee == null || !chairsee.equals(_r.chairsee))
                {
                    return false;
                }
            }
            if(chaircycle != _r.chaircycle)
            {
                if(chaircycle == null || _r.chaircycle == null || !chaircycle.equals(_r.chaircycle))
                {
                    return false;
                }
            }
            if(casecade != _r.casecade)
            {
                if(casecade == null || _r.casecade == null || !casecade.equals(_r.casecade))
                {
                    return false;
                }
            }
            if(schedule != _r.schedule)
            {
                if(schedule == null || _r.schedule == null || !schedule.equals(_r.schedule))
                {
                    return false;
                }
            }
            if(duration != _r.duration)
            {
                if(duration == null || _r.duration == null || !duration.equals(_r.duration))
                {
                    return false;
                }
            }
            if(date != _r.date)
            {
                if(date == null || _r.date == null || !date.equals(_r.date))
                {
                    return false;
                }
            }
            if(time != _r.time)
            {
                if(time == null || _r.time == null || !time.equals(_r.time))
                {
                    return false;
                }
            }
            if(week != _r.week)
            {
                if(week == null || _r.week == null || !week.equals(_r.week))
                {
                    return false;
                }
            }
            if(monthday != _r.monthday)
            {
                if(monthday == null || _r.monthday == null || !monthday.equals(_r.monthday))
                {
                    return false;
                }
            }
            if(autoConnectTimes != _r.autoConnectTimes)
            {
                return false;
            }
            if(autoSound != _r.autoSound)
            {
                if(autoSound == null || _r.autoSound == null || !autoSound.equals(_r.autoSound))
                {
                    return false;
                }
            }
            if(meetName != _r.meetName)
            {
                if(meetName == null || _r.meetName == null || !meetName.equals(_r.meetName))
                {
                    return false;
                }
            }
            if(delay != _r.delay)
            {
                if(delay == null || _r.delay == null || !delay.equals(_r.delay))
                {
                    return false;
                }
            }
            if(mnameFont != _r.mnameFont)
            {
                if(mnameFont == null || _r.mnameFont == null || !mnameFont.equals(_r.mnameFont))
                {
                    return false;
                }
            }
            if(nameColor != _r.nameColor)
            {
                if(nameColor == null || _r.nameColor == null || !nameColor.equals(_r.nameColor))
                {
                    return false;
                }
            }
            if(useColor != _r.useColor)
            {
                if(useColor == null || _r.useColor == null || !useColor.equals(_r.useColor))
                {
                    return false;
                }
            }
            if(mnameTop != _r.mnameTop)
            {
                if(mnameTop == null || _r.mnameTop == null || !mnameTop.equals(_r.mnameTop))
                {
                    return false;
                }
            }
            if(nameBgColor != _r.nameBgColor)
            {
                if(nameBgColor == null || _r.nameBgColor == null || !nameBgColor.equals(_r.nameBgColor))
                {
                    return false;
                }
            }
            if(useWord != _r.useWord)
            {
                if(useWord == null || _r.useWord == null || !useWord.equals(_r.useWord))
                {
                    return false;
                }
            }
            if(content != _r.content)
            {
                if(content == null || _r.content == null || !content.equals(_r.content))
                {
                    return false;
                }
            }
            if(scrollSpeed != _r.scrollSpeed)
            {
                if(scrollSpeed == null || _r.scrollSpeed == null || !scrollSpeed.equals(_r.scrollSpeed))
                {
                    return false;
                }
            }
            if(transparent != _r.transparent)
            {
                if(transparent == null || _r.transparent == null || !transparent.equals(_r.transparent))
                {
                    return false;
                }
            }
            if(conftransparent != _r.conftransparent)
            {
                if(conftransparent == null || _r.conftransparent == null || !conftransparent.equals(_r.conftransparent))
                {
                    return false;
                }
            }
            if(wordSize != _r.wordSize)
            {
                if(wordSize == null || _r.wordSize == null || !wordSize.equals(_r.wordSize))
                {
                    return false;
                }
            }
            if(wordLoction != _r.wordLoction)
            {
                if(wordLoction == null || _r.wordLoction == null || !wordLoction.equals(_r.wordLoction))
                {
                    return false;
                }
            }
            if(fontBgColor != _r.fontBgColor)
            {
                if(fontBgColor == null || _r.fontBgColor == null || !fontBgColor.equals(_r.fontBgColor))
                {
                    return false;
                }
            }
            if(fontColor != _r.fontColor)
            {
                if(fontColor == null || _r.fontColor == null || !fontColor.equals(_r.fontColor))
                {
                    return false;
                }
            }
            if(poll != _r.poll)
            {
                if(poll == null || _r.poll == null || !poll.equals(_r.poll))
                {
                    return false;
                }
            }
            if(pwd != _r.pwd)
            {
                if(pwd == null || _r.pwd == null || !pwd.equals(_r.pwd))
                {
                    return false;
                }
            }
            if(chpwd != _r.chpwd)
            {
                if(chpwd == null || _r.chpwd == null || !chpwd.equals(_r.chpwd))
                {
                    return false;
                }
            }
            if(audio != _r.audio)
            {
                if(audio == null || _r.audio == null || !audio.equals(_r.audio))
                {
                    return false;
                }
            }
            if(ext != _r.ext)
            {
                if(ext == null || _r.ext == null || !ext.equals(_r.ext))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 0;
        if(name != null)
        {
            __h = 5 * __h + name.hashCode();
        }
        if(lecture != null)
        {
            __h = 5 * __h + lecture.hashCode();
        }
        if(chair != null)
        {
            __h = 5 * __h + chair.hashCode();
        }
        if(chairsee != null)
        {
            __h = 5 * __h + chairsee.hashCode();
        }
        if(chaircycle != null)
        {
            __h = 5 * __h + chaircycle.hashCode();
        }
        if(casecade != null)
        {
            __h = 5 * __h + casecade.hashCode();
        }
        if(schedule != null)
        {
            __h = 5 * __h + schedule.hashCode();
        }
        if(duration != null)
        {
            __h = 5 * __h + duration.hashCode();
        }
        if(date != null)
        {
            __h = 5 * __h + date.hashCode();
        }
        if(time != null)
        {
            __h = 5 * __h + time.hashCode();
        }
        if(week != null)
        {
            __h = 5 * __h + week.hashCode();
        }
        if(monthday != null)
        {
            __h = 5 * __h + monthday.hashCode();
        }
        __h = 5 * __h + autoConnectTimes;
        if(autoSound != null)
        {
            __h = 5 * __h + autoSound.hashCode();
        }
        if(meetName != null)
        {
            __h = 5 * __h + meetName.hashCode();
        }
        if(delay != null)
        {
            __h = 5 * __h + delay.hashCode();
        }
        if(mnameFont != null)
        {
            __h = 5 * __h + mnameFont.hashCode();
        }
        if(nameColor != null)
        {
            __h = 5 * __h + nameColor.hashCode();
        }
        if(useColor != null)
        {
            __h = 5 * __h + useColor.hashCode();
        }
        if(mnameTop != null)
        {
            __h = 5 * __h + mnameTop.hashCode();
        }
        if(nameBgColor != null)
        {
            __h = 5 * __h + nameBgColor.hashCode();
        }
        if(useWord != null)
        {
            __h = 5 * __h + useWord.hashCode();
        }
        if(content != null)
        {
            __h = 5 * __h + content.hashCode();
        }
        if(scrollSpeed != null)
        {
            __h = 5 * __h + scrollSpeed.hashCode();
        }
        if(transparent != null)
        {
            __h = 5 * __h + transparent.hashCode();
        }
        if(conftransparent != null)
        {
            __h = 5 * __h + conftransparent.hashCode();
        }
        if(wordSize != null)
        {
            __h = 5 * __h + wordSize.hashCode();
        }
        if(wordLoction != null)
        {
            __h = 5 * __h + wordLoction.hashCode();
        }
        if(fontBgColor != null)
        {
            __h = 5 * __h + fontBgColor.hashCode();
        }
        if(fontColor != null)
        {
            __h = 5 * __h + fontColor.hashCode();
        }
        if(poll != null)
        {
            __h = 5 * __h + poll.hashCode();
        }
        if(pwd != null)
        {
            __h = 5 * __h + pwd.hashCode();
        }
        if(chpwd != null)
        {
            __h = 5 * __h + chpwd.hashCode();
        }
        if(audio != null)
        {
            __h = 5 * __h + audio.hashCode();
        }
        if(ext != null)
        {
            __h = 5 * __h + ext.hashCode();
        }
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(name);
        __os.writeString(lecture);
        __os.writeString(chair);
        __os.writeString(chairsee);
        __os.writeString(chaircycle);
        __os.writeString(casecade);
        __os.writeString(schedule);
        __os.writeString(duration);
        __os.writeString(date);
        __os.writeString(time);
        __os.writeString(week);
        __os.writeString(monthday);
        __os.writeInt(autoConnectTimes);
        __os.writeString(autoSound);
        __os.writeString(meetName);
        __os.writeString(delay);
        __os.writeString(mnameFont);
        __os.writeString(nameColor);
        __os.writeString(useColor);
        __os.writeString(mnameTop);
        __os.writeString(nameBgColor);
        __os.writeString(useWord);
        __os.writeString(content);
        __os.writeString(scrollSpeed);
        __os.writeString(transparent);
        __os.writeString(conftransparent);
        __os.writeString(wordSize);
        __os.writeString(wordLoction);
        __os.writeString(fontBgColor);
        __os.writeString(fontColor);
        __os.writeString(poll);
        __os.writeString(pwd);
        __os.writeString(chpwd);
        __os.writeString(audio);
        __os.writeString(ext);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        name = __is.readString();
        lecture = __is.readString();
        chair = __is.readString();
        chairsee = __is.readString();
        chaircycle = __is.readString();
        casecade = __is.readString();
        schedule = __is.readString();
        duration = __is.readString();
        date = __is.readString();
        time = __is.readString();
        week = __is.readString();
        monthday = __is.readString();
        autoConnectTimes = __is.readInt();
        autoSound = __is.readString();
        meetName = __is.readString();
        delay = __is.readString();
        mnameFont = __is.readString();
        nameColor = __is.readString();
        useColor = __is.readString();
        mnameTop = __is.readString();
        nameBgColor = __is.readString();
        useWord = __is.readString();
        content = __is.readString();
        scrollSpeed = __is.readString();
        transparent = __is.readString();
        conftransparent = __is.readString();
        wordSize = __is.readString();
        wordLoction = __is.readString();
        fontBgColor = __is.readString();
        fontColor = __is.readString();
        poll = __is.readString();
        pwd = __is.readString();
        chpwd = __is.readString();
        audio = __is.readString();
        ext = __is.readString();
    }
}
