// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_ClientMgrDel.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.vmediax.oneplusn.ice.mp.vmxMP;

public interface _ClientMgrDel extends vmxICE._ObjectMgrDel
{
    ClientPrx getClient(int index, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int getClientID(int index, Ice.StringHolder ID, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int getClientCount(Ice.IntHolder count, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int getClientType(ClientTypeHolder type, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int getIdleClient(Ice.StringHolder ID, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int getIdleClientList(int num, ClientIDListHolder list, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int freeClient(String ID, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int freeClientList(String[] list, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;
}
