// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `MessageClientKeyDisconnectType.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.vmediax.oneplusn.ice.mp.vmxMP;

/**
 * 客户端断开类型。其中"manual"表示用户正常挂断，其它为异常。
 **/
public interface MessageClientKeyDisconnectType
{
    String value = "ClientKeyDisconnectType";
}
