// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_ResourceDel.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package vmxICE;

public interface _ResourceDel extends _VMXObjectDel
{
    int enumInputNode(MediaNodeListHolder list, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int enumOutputNode(MediaNodeListHolder list, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;
}
