// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_VMXManagerOperations.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package vmxICE;

public interface _VMXManagerOperations extends _VMXObjectOperations
{
    /**
     * 注册一个对象池.
     * 
     * @param list 输出所有的对象池的ID的列表.
     * 
     * @param __current The Current object for the invocation.
     * @return 返回值为0代表成功，否则为失败的错误码.
     * 
     **/
    int registerMgr(String ID, String name, int objectType, Ice.Current __current);

    /**
     * 获取所有对象池的ID列表.
     * 
     * @param __current The Current object for the invocation.
     * @return 返回所有的对象池的ID的列表.
     * 
     **/
    ObjectMgrInfo[] getObjectMgrList(Ice.Current __current);
}
