// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `Callback_VMXObject_setParent.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package vmxICE;

/**
 * 给对象设置所有者，对象的大部分消息都会给所有者发送.
 * 
 **/

public abstract class Callback_VMXObject_setParent extends Ice.TwowayCallback
{
    public abstract void response(int __ret);

    public final void __completed(Ice.AsyncResult __result)
    {
        VMXObjectPrx __proxy = (VMXObjectPrx)__result.getProxy();
        int __ret = 0;
        try
        {
            __ret = __proxy.end_setParent(__result);
        }
        catch(Ice.LocalException __ex)
        {
            exception(__ex);
            return;
        }
        response(__ret);
    }
}
