// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `Callback_ObjectMgr_getIdleObjectList.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package vmxICE;

/**
 * 获取空闲的对象的ID列表，如果要求的数量大于存在的数量，则申请存在的数量并返回VMX_STATUS_ERR_OUT_OF_RESOURCE错误，实际申请到的数量可以通过查看list的数量获取.
 * 
 **/

public abstract class Callback_ObjectMgr_getIdleObjectList extends Ice.TwowayCallback
{
    public abstract void response(int __ret, String[] list);

    public final void __completed(Ice.AsyncResult __result)
    {
        ObjectMgrPrx __proxy = (ObjectMgrPrx)__result.getProxy();
        int __ret = 0;
        StringSeqHolder list = new StringSeqHolder();
        try
        {
            __ret = __proxy.end_getIdleObjectList(list, __result);
        }
        catch(Ice.LocalException __ex)
        {
            exception(__ex);
            return;
        }
        response(__ret, list.value);
    }
}
