// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `VMXSystem.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package vmxICE;

/**
 * [VMXSystem]是mmap6框架中对业务层系统的定义，描述了每个基于mmap6框架的系统的通用接口，如重置系统，设置配置项及系统之间的交互等，<b>接口定义还未完成</b>。
 **/
public interface VMXSystem extends Ice.Object,
                                   _VMXSystemOperations, _VMXSystemOperationsNC,
                                   VMXObject
{
}
