// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_MC2Del.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.vmediax.oneplusn.ice.api.vmxICE;

public interface _MC2Del extends vmxICE._VMXObjectDel
{
    int addTerminal(String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int addTerminalXML(String id, String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int updateTerminal(String name, String ip, String h323, String e164, String info, String called, String audio, String video, String fecc, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int deleteTerminal(String id, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<TerminalInfo> getTerminList(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<TerminalInfo> queryTerminList(String condition, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<TerminalInfo> queryNotConfTerminalList(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<TerminalInfo> getMemberListByConference(String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<TerminalInfo> getConnectMembersByConference(String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<TerminalInfo> getMemberListByConfForFlex(String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<TerminalInfo> getTempTerminList(String name, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<TerminalInfo> getTempTerminIdleList(String name, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<TerminalTypeInfo> getTemplateTerminalTypeList(String name, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int addTemplate(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int addTemplateXML(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.Map<java.lang.String, java.lang.String> getTerminalIdToIp(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int updateTemplate(String name, String e164, String info, java.util.List<java.lang.String> terminalListh, java.util.List<java.lang.String> terminalListm, java.util.List<java.lang.String> terminalListl, String vscreen, String vsize, String fps, String bandwidth, String bandwidthm, String vsizem, String bandwidthl, String vsizel, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int deleteTemplate(String name, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<TemplateInfo> getTemplateList(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<TemplateInfo> queryTemplateList(String condition, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int startConference(Conference conf, String templatename, StringListSHolder existsNumberClientNames, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int stopConference(String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<Conference> getConferenceList(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<Conference> getConferenceInfo(String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int start323Call(String terminalIp, String terminalName, String terminalType, String number, String qualityType, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int batchStart323Call(java.util.List<java.lang.String> terminalIpList, java.util.List<java.lang.String> terminalNameList, String number, String qualityType, StringListSHolder existTerminalNameList, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int stop323Call(String terminalIp, String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int disconnect323Call(String terminalIp, String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int connect323Call(String terminalIp, String terminalName, String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int stopSoftCall(String terminalName, String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int stopMobileCall(String terminalName, String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int disconnectAll(String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int connectAll(String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int muteMicrophone(String number, String terminal, String mic, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int muteSpeaker(String number, String terminal, String speaker, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int muteAllMicrophone(String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int openAllMicrophone(String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int muteAllSpeaker(String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int openAllSpeaker(String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    String getVscreen(String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<ScreenInfo> getScreenInfo(String number, String vscreen, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int setScreen(java.util.List<java.lang.String> terminalIp, java.util.List<java.lang.String> terminalName, String number, String vscreen, String index, String mode, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int setSubscreenMode(String number, String index, String mode, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int setQueue(String number, String index, String state, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int saveConferenceParam(String number, ConferenceParam cp, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<ConferenceParam> getConferenceParam(String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int saveTemplateParam(TemplateParamInfo tp, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<TemplateParamInfo> getTemplateParam(String templatename, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    String validateName(String name, String confId, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int setLecture(String number, String terminalIp, String terminalName, String lecture, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int setChair(String number, String terminalIp, String chair, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int setChairsee(String number, String mode, String[] terminalIp, String[] terminalName, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<ChairCycleInfo> getChaircycleList(String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<ChairCycleInfo> getChairCycleChoiceTerminals(String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<ChairCycleInfo> getChairseeList(String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int setFecc(String number, String terminalIp, int actionType, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int stopFecc(String number, String terminalIp, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int setQualityH323(String number, String terminalIp, String bandwidth, String vsize, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int setQualitySoft(String number, String terminalIp, String type, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int saveSysConfig(SysConfig sys, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<SysConfig> getSysConfig(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<IConfig> getIConfig(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int setIConfig(String name, String value, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int startConferenceP2p(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int stopConferenceP2p(String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<PacketInfo> getMemberPacketStatus(String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int setExt(String number, String terminalIp, String ext, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int[] getClientCache(String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    LicenseInfo getLicense(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int setRequestIFrame(String clientIP, String stream, String cmd, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int startRtspCall(String rtspName, String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int stopRtspCall(String number, String rtspName, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int startSipCall(String sipIp, String number, String qualityType, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int startSipCalled(String sipPhoneNumber, String number, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int stopSipCall(String number, String sipPhoneNumber, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int registerServer(String clientIP, String userName, String password, String domain, String regServerIP, String authName, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int addSip(SipInfo sipTerminalInfo, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int updateSip(SipInfo sipTerminalInfo, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int deleteSip(String sipIp, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    java.util.List<SipInfo> getSipList(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;
}
