// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_MCXMPPOperations.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.vmediax.oneplusn.ice.api.vmxICE;

public interface _MCXMPPOperations extends vmxICE._VMXObjectOperations
{
    int register(XmppUser user, Ice.Current __current);

    int deleteXmppUser(int userId, Ice.Current __current);

    java.util.List<XmppTree> getTreeList(Ice.Current __current);

    int addUser2Department(int userId, int departmentId, Ice.Current __current);

    int removeUserInDepart(int userId, int departmentId, Ice.Current __current);

    int modifyUserInDepart(int userId, int departmentId, Ice.Current __current);

    int addDepartment(XmppDepartment xd, Ice.Current __current);

    int modifyDepartment(XmppDepartment xd, Ice.Current __current);

    int deleteDepartment(int id, Ice.Current __current);

    int startConferenceXmpp(Ice.Current __current);

    int stopConferenceXmpp(String number, Ice.Current __current);
}
