// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_VMXSystemDel.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package vmxICE;

public interface _VMXSystemDel extends _VMXObjectDel
{
    int registerCallbackWithLocator(String ID, String locator, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int unregisterCallbackWithLocator(String ID, String locator, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int setConfigInfo(String name, String value, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int getConfigInfo(String name, Ice.StringHolder value, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int getConfigInfoList(StringSeqHolder configInfoList, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int setAdvanceConfigInfo(String name, String value, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int getAdvanceConfigInfo(String name, Ice.StringHolder value, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int getAdvanceConfigInfoList(ConfigInfoSeqHolder configInfoSequence, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int getLicense(String attrName, Ice.StringHolder attrValue, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;
}
