// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `Callback_MediaNodeMgr_recvMediaEx.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package vmxICE;

/**
 * 节点的接收数据函数，和recvMedia的区别在于可以接受多个池中的对象的数据，
 * 
 **/

public abstract class Callback_MediaNodeMgr_recvMediaEx extends Ice.OnewayCallback
{
}
