// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `Callback_VMXObject_enumProperty.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package vmxICE;

/**
 * 枚举对象的单个属性信息.
 * 
 **/

public abstract class Callback_VMXObject_enumProperty extends Ice.TwowayCallback
{
    public abstract void response(int __ret, PropertyInfo info);

    public final void __completed(Ice.AsyncResult __result)
    {
        VMXObjectPrx __proxy = (VMXObjectPrx)__result.getProxy();
        int __ret = 0;
        PropertyInfoHolder info = new PropertyInfoHolder();
        try
        {
            __ret = __proxy.end_enumProperty(info, __result);
        }
        catch(Ice.LocalException __ex)
        {
            exception(__ex);
            return;
        }
        response(__ret, info.value);
    }
}
