// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `Callback_VMXSystem_setAdvanceConfigInfo.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package vmxICE;

/**
 * 设置高级配置项的值，高级配置项和配置项的区别在于高级配置项不对普通用户公开，需要由集成商或者生产厂商进行配置。
 * 
 **/

public abstract class Callback_VMXSystem_setAdvanceConfigInfo extends Ice.TwowayCallback
{
    public abstract void response(int __ret);

    public final void __completed(Ice.AsyncResult __result)
    {
        VMXSystemPrx __proxy = (VMXSystemPrx)__result.getProxy();
        int __ret = 0;
        try
        {
            __ret = __proxy.end_setAdvanceConfigInfo(__result);
        }
        catch(Ice.LocalException __ex)
        {
            exception(__ex);
            return;
        }
        response(__ret);
    }
}
