// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `PadDirection.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package vmxICE;

/**
 * pad所处理的数据流的方向，输入或者输出
 **/
public enum PadDirection implements java.io.Serializable
{
    
    /**
     * 输入
     **/
    PDInput,
    
    /**
     * 输出
     **/
    PDOutput;

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeByte((byte)ordinal());
    }

    public static PadDirection
    __read(IceInternal.BasicStream __is)
    {
        int __v = __is.readByte(2);
        return values()[__v];
    }
}
