// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_ConferenceMgrOperations.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.vmediax.oneplusn.ice.mp.vmxMP;

/**
 * ConferenceMgr对象包含多个会议[Conference]对象，是多个会议对象的集合.
 * 
 **/
public interface _ConferenceMgrOperations extends vmxICE._ObjectMgrOperations
{
    /**
     * 获取会议对象的句柄.
     * 
     * @param index 用户想要获取的会议对象的索引.
     * 
     * @param __current The Current object for the invocation.
     * @return 如果成功，返回客户端对象的句柄，否则返回NULL.
     * 
     **/
    ConferencePrx getConference(int index, Ice.Current __current);

    /**
     * 获取会议端对象的ID.
     * 
     * @param index 用户想要获取的会议对象的索引.
     * @param ID 会议对象的ID.
     * 
     * @param __current The Current object for the invocation.
     * @return 返回值为0代表成功，否则为失败的错误码.
     * 
     **/
    int getConferenceID(int index, Ice.StringHolder ID, Ice.Current __current);

    /**
     * 获取集合中的会议数量.
     * 
     * @param count 输出参数，输出会议的数量.
     * 
     * @param __current The Current object for the invocation.
     * @return 返回值为0代表成功，否则为失败的错误码.
     * 
     **/
    int getConferenceCount(Ice.IntHolder count, Ice.Current __current);
}
