// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `_MPOperations.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.vmediax.oneplusn.ice.mp.vmxMP;

/**
 * MP对象为多媒体服务的抽象对象，通过它可以配置多媒体服务平台，查询包含的会议集合及客户端集合等,默认的MP的ICE ID为mp/0@mp-0.
 * 
 **/
public interface _MPOperations extends vmxICE._VMXSystemOperations
{
    /**
     * 获取[ClientMgr]集合的数量.
     * 
     * @param __current The Current object for the invocation.
     * @return ClientMgr的数量.
     * 
     **/
    int GetClientMgrCount(Ice.Current __current);

    /**
     * 获取某个[ClientMgr]的ID.
     * 
     * @param index 想要获取的ClientMgr的索引.
     * @param ID ClientMgr的ID.
     * 
     * @param __current The Current object for the invocation.
     * @return 返回值为0代表成功，否则为失败的错误码.
     * 
     **/
    int GetClientMgrByIndex(int index, Ice.StringHolder ID, Ice.Current __current);

    /**
     * 获取所有[ClientMgr]的ID列表.
     * 
     * @param list 所有的ClientMgr的ID的列表.
     * 
     * @param __current The Current object for the invocation.
     * @return 返回值为0代表成功，否则为失败的错误码.
     * 
     **/
    int GetClientMgrList(vmxICE.StringSeqHolder list, Ice.Current __current);

    /**
     * 获取MP包含的ConferenceMgr的数量.
     * 
     * @param __current The Current object for the invocation.
     * @return ConferenceMgr的数量.
     * 
     **/
    int GetConferenceMgrCount(Ice.Current __current);

    /**
     * 获取某个[ConferenceMgr]的ID.
     * 
     * @param index 想要获取的ConferenceMgr的索引.
     * @param ID ConferenceMgr的ID.
     * 
     * @param __current The Current object for the invocation.
     * @return 返回值为0代表成功，否则为失败的错误码.
     * 
     **/
    int GetConferenceMgrByIndex(int index, Ice.StringHolder ID, Ice.Current __current);

    /**
     * 获取所有[ConferenceMgr]的ID列表.
     * 
     * @param list 所有的ConferenceMgr的ID的列表.
     * 
     * @param __current The Current object for the invocation.
     * @return 返回值为0代表成功，否则为失败的错误码.
     * 
     **/
    int GetConferenceMgrList(vmxICE.StringSeqHolder list, Ice.Current __current);

    /**
     * 设置log图片，用于无视频图像时的分屏显示画面.
     * 
     * @param path log图片在服务器上的路径.
     * 
     * @param __current The Current object for the invocation.
     * @return 返回值为0代表成功，否则为失败的错误码.
     * 
     **/
    int setLogoPath(String path, Ice.Current __current);

    /**
     * 获取log图片的路径.
     * 
     * @param path log图片在服务器上的路径.
     * 
     * @param __current The Current object for the invocation.
     * @return 返回值为0代表成功，否则为失败的错误码.
     * 
     **/
    int getLogoPath(Ice.StringHolder path, Ice.Current __current);

    /**
     * 删除log图片.当无视频图像时，分屏将显示灰色.
     * 
     * @param __current The Current object for the invocation.
     * @return 返回值为0代表成功，否则为失败的错误码.
     * 
     **/
    int removeLogo(Ice.Current __current);
}
