// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `Callback_Client_connect.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.vmediax.oneplusn.ice.mp.vmxMP;

/**
 * 连接客户端,在调用该函数成功之后,客户端的状态会立即转换为[ConnectStateConnecting],但是该函数成功不代表连接已经成功,调用者需要根据连接成功的消息才能确定该客户端真正建立连接.
 * 
 **/

public abstract class Callback_Client_connect extends Ice.TwowayCallback
{
    public abstract void response(int __ret);

    public final void __completed(Ice.AsyncResult __result)
    {
        ClientPrx __proxy = (ClientPrx)__result.getProxy();
        int __ret = 0;
        try
        {
            __ret = __proxy.end_connect(__result);
        }
        catch(Ice.LocalException __ex)
        {
            exception(__ex);
            return;
        }
        response(__ret);
    }
}
