// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `MP.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.vmediax.oneplusn.ice.mp.vmxMP;

/**
 * MP对象为多媒体服务的抽象对象，通过它可以配置多媒体服务平台，查询包含的会议集合及客户端集合等,默认的MP的ICE ID为mp/0@mp-0.
 * 
 **/
public interface MP extends Ice.Object,
                            _MPOperations, _MPOperationsNC,
                            vmxICE.VMXSystem
{
}
