// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `SourceNamePosHolder.java'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.vmediax.oneplusn.ice.mp.vmxMP;

public final class SourceNamePosHolder
{
    public
    SourceNamePosHolder()
    {
    }

    public
    SourceNamePosHolder(SourceNamePos value)
    {
        this.value = value;
    }

    public SourceNamePos value;
}
